### ISSUE TITLE
训练过程中bert模型的的参数有更新吗？

### ISSUE THREAD

**Issue by ninghongbo123** [macanv/BERT-BiLSTM-CRF-NER#105]
请问bert只是提供特征，还是说会进行tune，以及它调整的具体哪些层的参数？

**Comment by macanv** [comment]
会，具体看代码。

**Comment by kFoodie** [comment]
CUDA_VISIBLE_DEVICES=7 \
python bert_lstm_ner.py \
--task_name="NER" \
--do_train=True \
--do_eval=True \
--do_predict=True \
--data_dir=/container_data/zgk/Pycharm/BERT-BiLSTM-CRF-NER/data \
--vocab_file=/container_data/zgk/Pycharm/BertModel/vocab.txt  \
--bert_config_file=/container_data/zgk/Pycharm/BertModel/bert_config.json \
--init_checkpoint=/container_data/zgk/Pycharm/BertModel/bert_model.ckpt \
--max_seq_length=512 \
--train_batch_size=8 \
--learning_rate=2e-5 \
--num_train_epochs=3.0 \
--output_dir=../output/result_dir/
怎么训练不了的样子？没反应？？

**Comment by macanv** [comment]
max_seq_length 改小点，具体多小看你机器，我的默认配置使用的是24G显存得卡

**Comment by macanv** [comment]
@kFoodie max_seq_length 改小点，具体多小看你机器，我的默认配置使用的是24G显存得卡

**Comment by kFoodie** [comment]
> @kFoodie max_seq_length 改小点，具体多小看你机器，我的默认配置使用的是24G显存得卡

感谢大神回复。我想请问一下，280M训练集，30M验证集，2080Ti显卡，11G显存，batchsize=6, maxlen=500，大概要训练多久……

**Comment by beijingzhang** [comment]
> > @kFoodie max_seq_length 改小点，具体多小看你机器，我的默认配置使用的是24G显存得卡
> 
> 感谢大神回复。我想请问一下，280M训练集，30M验证集，2080Ti显卡，11G显存，batchsize=6, maxlen=500，大概要训练多久……

你好，能给我一份你的数据集吗？我的9M的数据集一直提示training data is so small  不知道该如何解决。邮箱：1309045653@qq.com

**Comment by macanv** [comment]
training data is so small ，如果不是数据太少，就是你的数据格式有问题。请检查一下，读数据的时候，是否正常。
