### ISSUE TITLE
ner批量预测时，长度过长的句子 lenght>10000的容易出错，要么卡死gpu，报value error:empty string，要么就是一直卡着

### ISSUE THREAD

**Issue by zhangxiangping** [macanv/BERT-BiLSTM-CRF-NER#108]
ner批量预测时，长度过长的句子 lenght>10000的容易出错，要么卡死gpu，报value error:empty string，要么就是一直卡着

**Comment by zhangxiangping** [comment]
..自问自答，batch_size调高，或升级gpu可解决

**Comment by Machine-Tom** [comment]
> ..自问自答，batch_size调高，或升级gpu可解决

请问你是输入未标注文本批量预测吗？如果是，可以请教一下你具体是怎么做的吗
