### ISSUE TITLE
how to use http server?

### ISSUE THREAD

**Issue by shunyuanxue** [macanv/BERT-BiLSTM-CRF-NER#110]
hi macanv！
为了启动http服务，我参照hanxiao的bert service执行了命令 
bert-base-serving-start 
-model_dir ... 
-bert_model_... 
-model_pb_dir ... 
-mode NER 
-http_port 8125 
然后报了error需要 install bert-serving-server[http]，我安装了bert-serving-server[http]之后仍然报这个错误，请问是我使用http服务的方式有问题吗

**Comment by macanv** [comment]
不需要了吧，，，我测试的时候，指定了port就可以启动http service的。因为这块的代码没改动，直接使用hanxiao的服务端代码，因为我也不会http，，，
