### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by kFoodie** [macanv/BERT-BiLSTM-CRF-NER#111]
![image](https://user-images.githubusercontent.com/16017418/56679467-b8821980-66f7-11e9-93a1-64bd1d6ee945.png)
我在参数里面设置了-clean False，但是实际上运行的还是clean True。
我只能通过改源码来解决了……

**Comment by gao-lex** [comment]
对啊，clean参数不管用啊，老哥怎么解决的

**Comment by gao-lex** [comment]
@kFoodie
