### ISSUE TITLE
求教大佬，就是预测出来的实体中有的字会出现unk这种情况？

### ISSUE THREAD

**Issue by skywindy** [macanv/BERT-BiLSTM-CRF-NER#112]
您好，就是我参考相关代码，用bert实现实体识别，识别的结果出现unk这种字情况，这种问题如何解决？

**Comment by skywindy** [comment]
![捕获2](https://user-images.githubusercontent.com/9455629/56800424-88e52580-684d-11e9-9957-02b0182ef59d.PNG)
![捕获](https://user-images.githubusercontent.com/9455629/56800425-8aaee900-684d-11e9-818a-ce69aeae1aaa.PNG)

**Comment by skywindy** [comment]
![image](https://user-images.githubusercontent.com/9455629/56857705-8694df80-69a3-11e9-9aa7-1f13985d898e.png)

**Comment by skywindy** [comment]
解决办法是将wordpiece_tokenizer去掉了
![image](https://user-images.githubusercontent.com/9455629/56858100-8991cf00-69a7-11e9-8eef-9fea9ff0c0a0.png)

**Comment by macanv** [comment]
这样的话，是去掉了wordpice？？？

**Comment by skywindy** [comment]
我是在预测的时候去掉了。训练的时候还是原来的方式，不知道训练的时候去掉会有多大影响，我想应该只会对英文预测有影响吧。------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>
发送时间: 2019年4月28日(星期天) 中午11:52
收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com>;
抄送: "wjian"<760201005@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [macanv/BERT-BiLSTM-CRF-NER] 求教大佬，就是预测出来的实体中有的字会出现unk这种情况？ (#112)



这样的话，是去掉了wordpice？？？
 
&mdash;

**Comment by skywindy** [comment]
大佬还有什么好办法来解决这种问题？我朋友用pytorch的bert好像没有unk，我看了他的那个没有去掉wordpiece，不知道那个是如何解决的------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>
发送时间: 2019年4月28日(星期天) 中午11:52
收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com>;
抄送: "wjian"<760201005@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [macanv/BERT-BiLSTM-CRF-NER] 求教大佬，就是预测出来的实体中有的字会出现unk这种情况？ (#112)



这样的话，是去掉了wordpice？？？
 
&mdash;

**Comment by macanv** [comment]
不知道torch咋弄的，不过你不用unk，那么就是wordpice分，unk不出现也在情理之中吧

**Comment by macanv** [comment]
wordpice出现的是###xxx这种。

**Comment by a461925358** [comment]
> 大佬还有什么好办法来解决这种问题？我朋友用pytorch的bert好像没有unk，我看了他的那个没有去掉wordpiece，不知道那个是如何解决的------------------ 原始邮件 ------------------ 发件人: "notifications"<notifications@github.com> 发送时间: 2019年4月28日(星期天) 中午11:52 收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com>; 抄送: "wjian"<760201005@qq.com>;"State change"<state_change@noreply.github.com>; 主题: Re: [macanv/BERT-BiLSTM-CRF-NER] 求教大佬，就是预测出来的实体中有的字会出现unk这种情况？ (#112) 这样的话，是去掉了wordpice？？？ &mdash; You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

wordpice  是解决类似min##yan##g这种问题的,UNK是bert预训练vocab.txt中没有的字,不明白 怎么可以解决

**Comment by a461925358** [comment]
不过  我试了  大佬的方法确实可以解决   但我还没搞明白原理
