### ISSUE TITLE
请问您实体识别预测的速度是多少s?

### ISSUE THREAD

**Issue by Single430** [macanv/BERT-BiLSTM-CRF-NER#113]
@macanv 
max_seq_length=512
i5-4590, 预测一条大概１ｓ左右

请问您实体识别预测的速度是多少s? 怎么才能提高这个速度？

**Comment by macanv** [comment]
效率提升策略：
1. batch
2. 多线程
3. 使用GPU
4. 改进BERT模型
5.。。。

**Comment by Single430** [comment]
@macanv 

1. 我这边有测试过batch  速度提升不明显 (放弃)
2. python使用多线程........有试过多进程,但是会出错(tensorflow模型貌似不能, 未解决, (放弃))
3. GPU   这个没办法,没有....(放弃)
4. 有将BERT模型参数调小几个档次, 但是R, P F1 变化明显,  "num_attention_heads": 12, 
  "num_hidden_layers": 12,    都改成8的时候,结果还能接受  (+1)

如果您对1,2有什么好的想法请告诉我,谢谢

**Comment by macanv** [comment]
本项目基本可以进行batch和多线程的预测。
取att 的top层数，效率也不会有很大的提升。
