### ISSUE TITLE
assert语句判别tensorflow版本

### ISSUE THREAD

**Issue by pengyong94** [macanv/BERT-BiLSTM-CRF-NER#114]
大佬，我在ubtuntu18下面执行bert-base-serving-start -help出现报错，说是需要tensorflow1.10以上版本。我自己的是tensorflow1.8版本。看到报错中出现以下assert语句。菜鸟弱弱问一句这样判别版本是不是不太合理啊
`assert int(tf_ver[0]) >= 1 and int(tf_ver[1]) >= 10, 'Tensorflow >=1.10 is required!'
AssertionError: Tensorflow >=1.10 is required!`

**Comment by macanv** [comment]
这个assert貌似是来自bert as service
不过我的确菜鸟水平，如果您觉得怎么判断好，提request吧，我merge

**Comment by macanv** [comment]
这个assert貌似是来自bert as service
不过我的确菜鸟水平，如果您觉得怎么判断好，提request吧，我merge

**Comment by macanv** [comment]
这个assert貌似是来自bert as service
不过我的确菜鸟水平，如果您觉得怎么判断好，提request吧，我merge
