### ISSUE TITLE
bert_lstm_ner.py为啥里面找不到bert_path呢

### ISSUE THREAD

**Issue by jufengada** [macanv/BERT-BiLSTM-CRF-NER#116]
if os.name == 'nt': #windows path config
   bert_path = '{your BERT model path}'
   root_path = '{project path}'
else: # linux path config
   bert_path = '{your BERT model path}'
   root_path = '{project path}'
-----------------------------------------------------------------------
想进行上面那一个步骤，请问为啥里面找不到bert_path呢？

**Comment by wshzd** [comment]
这个我也找不到，而且只使用crf解码也不是450行

**Comment by JovenChu** [comment]
@jufengada 这两个参数的设置在与bert_lstm_ner.py同目录下的train_helper.py中找到。如果是命令行训练记得在python软件包中更改才会生效～

**Comment by nuass** [comment]
@JovenChu 命令行执行在那里改，我也是改train_helper.py 没生效。

**Comment by nuass** [comment]
@jufengada 在请教，bert-base-serving-start \ 这个命两行，执行的是哪个文件？

**Comment by macanv** [comment]
全部的运行代码，在run/__init__.py中，大家可以自行查看。

**Comment by wangjiaxu** [comment]
> @JovenChu 命令行执行在那里改，我也是改train_helper.py 没生效。

同修改没生效，请问是如何解决的呢？  @macanv @JovenChu
