### ISSUE TITLE
发现一个BUG

### ISSUE THREAD

**Issue by cyl250** [macanv/BERT-BiLSTM-CRF-NER#117]
中英交错的时候会出现，标注的个数比中文的个数少的情况，（中文）（英文）（中文）这个，就会出现不对应的问题。请问有这个问题么？

**Comment by cyl250** [comment]
我是用bert_server的方式进行实体识别的

**Comment by jufengada** [comment]
你好，你有出现运行python bert_lstm_crf.py没反应呢？

**Comment by macanv** [comment]
试一下自定义切

**Comment by cyl250** [comment]
问题解决，老板，你的代码没问题，是我蠢了，bc.encode()放入两维的列表问题得解，我这边放入了字符串列表，并且删除了is_tokenized=True这一个参数，于是就出现了中英文交替会导致预测标注个数比字数少1的问题。
