### ISSUE TITLE
为啥运行bert_lstm_ner.py没有反应呢？

### ISSUE THREAD

**Issue by jufengada** [macanv/BERT-BiLSTM-CRF-NER#118]
python3 bert_lstm_ner.py  --task_name="NER"  \--do_train=True   \
                  --do_eval=True   \
                  --do_predict=True \
                  --data_dir=NERdata   \
                  --vocab_file=/home/TengWei/BERT-BiLSTM-CRF-NER-master/chinese_L-12_H-768_A-12/vocab.txt \ 
                  --bert_config_file=/home/TengWei/BERT-BiLSTM-CRF-NER-master/chinese_L-12_H-768_A-12/bert_config.json \  
                  --init_checkpoint=/home/TengWei/BERT-BiLSTM-CRF-NER-master/chinese_L-12_H-768_A-12/bert_model.ckpt   \
                  --max_seq_length=128   \
                  --train_batch_size=32   \
                  --learning_rate=2e-5   \
                  --num_train_epochs=3.0   \
                  --output_dir=./output/result_dir/

**Comment by bertramlau** [comment]
这个代码没有main函数，需要自己修改处理
