### ISSUE TITLE
评价指标

### ISSUE THREAD

**Issue by HAWLYQ** [macanv/BERT-BiLSTM-CRF-NER#12]
@macanv 您好。我对您项目中的评价指标有点疑惑。我看代码里好像是以tag为单位计算的F1（例如 B-LOC，I-LOC，B-ORG, I-ORG 是单独计算的），但NER一般是以实体类型为单位计算的（如LOC, ORG）。您项目里附加的正确的评测脚本conlleva好像并没有用上。

**Comment by macanv** [comment]
用上了，在predicted 阶段。
