### ISSUE TITLE
请问一个关于模型超参数的问题

### ISSUE THREAD

**Issue by 18256065810** [macanv/BERT-BiLSTM-CRF-NER#125]
作者，您好！我基于您用默认参数训练出来的模型
![dsds](https://user-images.githubusercontent.com/39405529/57606924-8b10e900-759c-11e9-8b4b-134f46c955e7.png)在我的测试集上测试了一下实体识别的效果，其中ORG主体的正确率是88%，然后我基于默认参数(batch_size=32,learning_rate=2e-5,dropout_date=0.5,num_train_epochs=15.0)在您提供的百万token的训练集上训练模型，然后在同样的测试集上测试效果，发现ORG主体的正确率只有75%，差距有13个点，另外其他指标都比您提供的结果要低。所以我能问一下您当时训练这个模型时使用的超参数(learning_rate/batch_size/dropout_rate等)是什么样的吗？

**Comment by macanv** [comment]
我基本没有调参数，你看到的是什么参数就是这个

**Comment by 18256065810** [comment]
Thanks!
