### ISSUE TITLE
Is there some special for the label format?

### ISSUE THREAD

**Issue by bifeng** [macanv/BERT-BiLSTM-CRF-NER#127]
I am use the label start with 'B_...' 、'I_...' ..., but it failed to predict result. Why the '_' is not effect ?

**Comment by macanv** [comment]
the scripyt of conlleval.py  just support '-' format.

**Comment by bifeng** [comment]
Like you said, it should just affect the `label_test.txt` file, it does not affect the training ?

**Comment by macanv** [comment]
yes.
