### ISSUE TITLE
跑不动，也不报错，求指导！

### ISSUE THREAD

**Issue by wonder-hy** [macanv/BERT-BiLSTM-CRF-NER#129]
batch_size 都改到8了
还是一直停在这里不动
![image](https://user-images.githubusercontent.com/45653189/57761341-e4f5e800-772f-11e9-9dd3-37897384d350.png)

**Comment by charlesfufu** [comment]
> batch_size 都改到8了
> 还是一直停在这里不动
> ![image](https://user-images.githubusercontent.com/45653189/57761341-e4f5e800-772f-11e9-9dd3-37897384d350.png)

目前有解决吗？

**Comment by macanv** [comment]
就是停在这里啊，日志有一点bug,你可以看一下输出路径是否有新的ckpt写入了。
