### ISSUE TITLE
迭代少量Epoch

### ISSUE THREAD

**Issue by pkuweijia** [macanv/BERT-BiLSTM-CRF-NER#13]
当迭代轮数较少的时候，比如训练时跑了3个epoch，出现token丢失的情况有遇到吗？
比如test data：
word1，tag1
word2，tag2
word3，tag3

预测的时候变成了：
word1，tag1'
word2，tag2'
..
word3 没了

**Comment by pkuweijia** [comment]
我知道了，predict部分代码有bug。序列中预测出的CLS和SEQ标签应该作为bad case而不是continue过去。

预测时应该限制开始输出的位置和结束输出的位置。保证输出的tag序列长度 = word list或者tag list真值的长度。

**Comment by macanv** [comment]
是的，这一块我也很烦躁，最近在写毕设，没时间整，如果您修改成功了，麻烦提交一下，让更多童鞋能一起学习，谢谢~~
