### ISSUE TITLE
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory chinese_L-12_H-768_A-12/

### ISSUE THREAD

**Issue by icegomic** [macanv/BERT-BiLSTM-CRF-NER#131]
启动训练配置
nohup bert-base-ner-train -data_dir train/ -output_dir result/ -init_checkpoint chinese_L-12_H-768_A-12/bert_model.ckpt -bert_config_file chinese_L-12_H-768_A-12/bert_config.json -vocab_file chinese_L-12_H-768_A-12/vocab.txt &
我下载的model里面是这几个文件
bert_config.json    
bert_model.ckpt.data-00000-of-00001  
bert_model.ckpt.index 
bert_model.ckpt.meta

提示错误ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory chinese_L-12_H-768_A-12/

**Comment by Apollo2Mars** [comment]
同问

**Comment by Apollo2Mars** [comment]
应该是路径错误，路径正确后是没有问题的@icegomic

**Comment by macanv** [comment]
是的，改成绝对路径再试试吧。测试很多次，没有问题，这一块。

**Comment by zhangjiantong** [comment]
我也是这种问题，是绝对路径。

**Comment by liushaoqian** [comment]
> 我也是这种问题，是绝对路径。

你解决了吗，我也遇到了同样的问题，我用的是CPU，有人说可能是显卡显存不足所导致的

**Comment by liushaoqian** [comment]
> 启动训练配置 nohup bert-base-ner-train -data_dir train/ -output_dir result/ -init_checkpoint chinese_L-12_H-768_A-12/bert_model.ckpt -bert_config_file chinese_L-12_H-768_A-12/bert_config.json -vocab_file chinese_L-12_H-768_A-12/vocab.txt & 我下载的model里面是这几个文件 bert_config.json bert_model.ckpt.data-00000-of-00001 bert_model.ckpt.index bert_model.ckpt.meta
> 
> 提示错误ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory chinese_L-12_H-768_A-12/

同问，我也出现了这样的问题

**Comment by qyuan2** [comment]
同问
