### ISSUE TITLE
识别出错

### ISSUE THREAD

**Issue by lvjianjin** [macanv/BERT-BiLSTM-CRF-NER#134]
我在用自己的数据以及自己的标签上训练了一个新的模型，但是出现了 输入文本为两个字符 但是识别的输出结果为 三个字符 的情况。请问这是由什么引起的。thanks

**Comment by macanv** [comment]
BERT默认的切词导致的，你可以看下原始项目细节，然后，可以自定义切。

**Comment by lvjianjin** [comment]
好的 谢谢
