### ISSUE TITLE
ner retuen tokens

### ISSUE THREAD

**Issue by nobrowning** [macanv/BERT-BiLSTM-CRF-NER#135]
我在使用的时候发现，将本程序作为NER服务时，只返回标签序列。这样对于Client来说，得到的太少了。还需要再对文本做一遍分词。
若Client的分词结果(tokens)与NER Server内部的分词结果不一致，那么得到的标签序列也是没有意义的。
所以我修改了一点您的代码，使得NER服务会返回tokens.希望您以后可以补上这个小遗憾。
https://github.com/nobrowning/BERT-BiLSTM-CRF-NER

**Comment by macanv** [comment]
good and thx.
