### ISSUE TITLE
预测结果有时不连续什么原因？

### ISSUE THREAD

**Issue by nuass** [macanv/BERT-BiLSTM-CRF-NER#141]
偶然会出现，错误的预测，如下：
![image](https://user-images.githubusercontent.com/22679115/58620933-dea06800-82fa-11e9-9df3-914ee307e8d9.png)
大部分是对的，如下：

![image](https://user-images.githubusercontent.com/22679115/58621016-04c60800-82fb-11e9-8bc0-0f1dde5f3bf2.png)

**Comment by macanv** [comment]
你的输入是不是会有unk或者存在英文字符？

**Comment by nuass** [comment]
问题应该是出在英文字符。Thanks

**Comment by lsy641** [comment]
英语不是默认支持吗，那怎么跳过英文了？
