### ISSUE TITLE
显存不够

### ISSUE THREAD

**Issue by 18813055625** [macanv/BERT-BiLSTM-CRF-NER#143]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
在客户端训练的时候会出现显存不够用的情况，用代码训练不会出现这个情况，有谁遇到了吗？

**Comment by taichuai** [comment]
我也遇到过，调小batch_size吧

**Comment by 18813055625** [comment]
batch_size太小了，训练好慢

**Comment by taichuai** [comment]
那也没办法。。。
