### ISSUE TITLE
NER中文全为0？？

### ISSUE THREAD

**Issue by Suncicie** [macanv/BERT-BiLSTM-CRF-NER#161]
加载作者训练好的ner, encode无最终结果返回， 看中间结果发现encode全为0 ？ 不清楚0（零）是怎么来的，label也是从1开始，只有mask使用0, 全标注成了mask的值？？

**Comment by Suncicie** [comment]
作者代码有点小bug, 挺的训练好的模型不可用，已pull

**Comment by Machine-Tom** [comment]
> 作者代码有点小bug, 挺的训练好的模型不可用，已pull

您好，我也遇到了这个问题，请问可以分享一下你发现的bug吗？
