### ISSUE TITLE
输入某些单个字符返回为空

### ISSUE THREAD

**Issue by zhangkun9613** [macanv/BERT-BiLSTM-CRF-NER#163]
目前发现输入 “跳”，“吃”时模型会返回为空，请问是由于什么导致的
![image](https://user-images.githubusercontent.com/20919920/59829654-8942fe00-9370-11e9-9497-f5190dee3bea.png)
模型预测的时候也有这个问题，

**Comment by zhangkun9613** [comment]
模型在预测的时候也会出现这个问题

**Comment by zhangkun9613** [comment]
![image](https://user-images.githubusercontent.com/20919920/59961136-d1dff000-9505-11e9-8d58-868c2435c649.png)
![image](https://user-images.githubusercontent.com/20919920/59961137-dc01ee80-9505-11e9-8742-40190da25075.png)
检查后发现是模型预测值的问题，实体的tag识别成了[CLS]，请问这种情况是不是应该通过后处理来修复，还是我模型训练过程出问题导致的

**Comment by Machine-Tom** [comment]
请问你是怎么解决的？
