### ISSUE TITLE
效果挺好的，人名识别的精度到了97%

### ISSUE THREAD

**Issue by zongyanke** [macanv/BERT-BiLSTM-CRF-NER#177]
![image](https://user-images.githubusercontent.com/26877961/60476080-c3839800-9cac-11e9-9711-2f408aa9331e.png)

接下来准备用自己的语料训练一下，准备做垂直领域的实体识别，识别音乐和阅读领域里面的歌手、歌名、作者、书名。之前用纯粹的crf做过，但是由于某些网络作者和很长的歌名、书名识别效果不好。这个对于非常正常、传统的中文人名识别的不错，对于网络小说作者、像一句话一样的歌名的识别有待验证。

对了在这里我问一下假如要识别中英混杂的句子里面的歌手名和歌曲名的话，我通过下面的数据集进行训练是否可行呢，会不会有英文无法识别的情况
"我要听韩红的青藏高原"( O O O B-PER I-PER O B-SNG I-SNG I-SNG I-SNG）、
"我要听Adele的Rolling in the deep"（O O O B-PER O B-SNG I-SNG I-SNG I-SNG）

对了我在运行你的模型的时候发现你是将训练和评估放在一起的，但是这个api好像有问题，会提示stop_if_no_decrease_hook不存在，后面我将训练和评估过程分开了，我的环境是tensorflow1.14.0+cuda10.0

**Comment by zxxufo008** [comment]
> ![image](https://user-images.githubusercontent.com/26877961/60476080-c3839800-9cac-11e9-9711-2f408aa9331e.png)
> 
> 接下来准备用自己的语料训练一下，准备做垂直领域的实体识别，识别音乐和阅读领域里面的歌手、歌名、作者、书名。之前用纯粹的crf做过，但是由于某些网络作者和很长的歌名、书名识别效果不好。这个对于非常正常、传统的中文人名识别的不错，对于网络小说作者、像一句话一样的歌名的识别有待验证。
> 
> 对了在这里我问一下假如要识别中英混杂的句子里面的歌手名和歌曲名的话，我通过下面的数据集进行训练是否可行呢，会不会有英文无法识别的情况
> "我要听韩红的青藏高原"( O O O B-PER I-PER O B-SNG I-SNG I-SNG I-SNG）、
> "我要听Adele的Rolling in the deep"（O O O B-PER O B-SNG I-SNG I-SNG I-SNG）
> 
> 对了我在运行你的模型的时候发现你是将训练和评估放在一起的，但是这个api好像有问题，会提示stop_if_no_decrease_hook不存在，后面我将训练和评估过程分开了，我的环境是tensorflow1.14.0+cuda10.0

你好，我也是报stop_if_no_decrease_hook不存在，你后来是如何操作，让训练跑通的啊

**Comment by just-do-it-for-everything** [comment]
> ![image](https://user-images.githubusercontent.com/26877961/60476080-c3839800-9cac-11e9-9711-2f408aa9331e.png)
> 
> 接下来准备用自己的语料训练一下，准备做垂直领域的实体识别，识别音乐和阅读领域里面的歌手、歌名、作者、书名。之前用纯粹的crf做过，但是由于某些网络作者和很长的歌名、书名识别效果不好。这个对于非常正常、传统的中文人名识别的不错，对于网络小说作者、像一句话一样的歌名的识别有待验证。
> 
> 对了在这里我问一下假如要识别中英混杂的句子里面的歌手名和歌曲名的话，我通过下面的数据集进行训练是否可行呢，会不会有英文无法识别的情况
> "我要听韩红的青藏高原"( O O O B-PER I-PER O B-SNG I-SNG I-SNG I-SNG）、
> "我要听Adele的Rolling in the deep"（O O O B-PER O B-SNG I-SNG I-SNG I-SNG）
> 
> 对了我在运行你的模型的时候发现你是将训练和评估放在一起的，但是这个api好像有问题，会提示stop_if_no_decrease_hook不存在，后面我将训练和评估过程分开了，我的环境是tensorflow1.14.0+cuda10.0

你后面是用Bilstm+crf还是crf only

**Comment by macanv** [comment]
1.4没测试过，我用的1.2，谢谢~~

**Comment by xiangbei1997** [comment]
您好,请问一下您是如何根据语料训练出来的模型呢?大神?

**Comment by iboying** [comment]
`stop_if_no_decrease_hook` 的问题，改成这个就行了：
tf.estimator.experimental.stop_if_no_decrease_hook

**Comment by xiangbei1997** [comment]
> `stop_if_no_decrease_hook` 的问题，改成这个就行了：
> tf.estimator.experimental.stop_if_no_decrease_hook

多谢老哥

**Comment by xmy7216** [comment]
> ![image](https://user-images.githubusercontent.com/26877961/60476080-c3839800-9cac-11e9-9711-2f408aa9331e.png)
> 
> 接下来准备用自己的语料训练一下，准备做垂直领域的实体识别，识别音乐和阅读领域里面的歌手、歌名、作者、书名。之前用纯粹的crf做过，但是由于某些网络作者和很长的歌名、书名识别效果不好。这个对于非常正常、传统的中文人名识别的不错，对于网络小说作者、像一句话一样的歌名的识别有待验证。
> 
> 对了在这里我问一下假如要识别中英混杂的句子里面的歌手名和歌曲名的话，我通过下面的数据集进行训练是否可行呢，会不会有英文无法识别的情况
> "我要听韩红的青藏高原"( O O O B-PER I-PER O B-SNG I-SNG I-SNG I-SNG）、
> "我要听Adele的Rolling in the deep"（O O O B-PER O B-SNG I-SNG I-SNG I-SNG）
> 
> 对了我在运行你的模型的时候发现你是将训练和评估放在一起的，但是这个api好像有问题，会提示stop_if_no_decrease_hook不存在，后面我将训练和评估过程分开了，我的环境是tensorflow1.14.0+cuda10.0

您好，请问您做垂直领域音乐类的识别用的什么训练数据呢？

**Comment by xxllp** [comment]
> 1.4没测试过，我用的1.2，谢谢~~

你这版本真低
