### ISSUE TITLE
How can I train it by using other language datasets?

### ISSUE THREAD

**Issue by sugiyamath** [macanv/BERT-BiLSTM-CRF-NER#178]
This project seems to train Chinese, but I want to train other languages like Japanese, English, etc. However, Chinese tokenizer seems to tokenize as characters but not words, so I'm not sure whether this project can apply to other languages or not.

For example, Japanese training data is like this:

```
私 O
は O
バラク B-Person
・ I-Person
オバマ I-Person
元 O
大統領 O
を O
尊敬 O
し O
て O
いる O
```

but, I don't want to tokenize them as Chinese characters.
Could you tell me how can train it as non-Chinese languages?

**Comment by sugiyamath** [comment]
I still can't solve this issue, but I decide to use ```BrikerMan/Kashgari``` instead of this project.

**Comment by echan00** [comment]
If you don't mind me asking, was tokenization of words the main issue? What did Kashgari do that made it work?

**Comment by sugiyamath** [comment]
Tokenization is the issue, but Kashigari is the another BERT-bilstm-crf model that is easy to use.
