### ISSUE TITLE
ner任务时，输入的字符串上长度和返回的标签长度不一致

### ISSUE THREAD

**Issue by ghui0318** [macanv/BERT-BiLSTM-CRF-NER#180]
![a](https://user-images.githubusercontent.com/34462009/60788255-d99ec600-a18e-11e9-8745-a5d2231f47d6.jpg)

**Comment by macanv** [comment]
自定义分字。

**Comment by andglf** [comment]
这个应该怎么自定义呢

**Comment by HandsomeCao** [comment]
请问一下我也遇见了这个问题，使用(list(str),istokenized=True)也会长度不一致，怎么解决呢？

**Comment by qubo** [comment]
将句子做成数组，然后修改
    rst = bc.encode([str, str])  #测试同时输入两个句子，多个输入同理
为
    rst = bc.encode([str, str], is_tokenized=True)  #测试同时输入两个句子，多个输入同理
