### ISSUE TITLE
vocab.txt里的##号是怎么回事呢

### ISSUE THREAD

**Issue by cwj** [macanv/BERT-BiLSTM-CRF-NER#185]
请问大家，在vocab.txt这个文件里，有很多#号，这是怎么回事呢，是对词没做清洗么？
survey
##016
1979
1950
wikia
##32
##017
5g
cbc
##tor
##kg
1983
##rt
##14
campaign
store
2500
os
##ct
##ts
##°
170
api
##ns

**Comment by illuminascent** [comment]
是sentencepiece分出来的sub token，比如nicely会被分为nice ##ly，可以编码很多词性变化、助词等等，节省词典空间。当然在中文领域显然没有英语那么大作用。
