### ISSUE TITLE
Early stopping around the best checkpoint ?

### ISSUE THREAD

**Issue by bifeng** [macanv/BERT-BiLSTM-CRF-NER#187]
In the early stopping function, max_steps_without_decrease is:
`        num_train_steps = int(
            len(train_examples) * 1.0 / args.batch_size * args.num_train_epochs)`
So, it means in the whole training periods, if the metrics didn't decrease, then stop. In this setting, the model seems didn't save the best checkpoint (For example, num_trian_steps=10000, and the best checkpoint at step=1000, then you still training other 9000 steps before stop.
Maybe should set the `max_steps_without_decrease` around 1000 ?

**Comment by macanv** [comment]
yet, you are right.
I will update that bug soon
