### ISSUE TITLE
老哥新的基于源码的训练已经不能用了吗?这个已经找不到了

### ISSUE THREAD

**Issue by xiangbei1997** [macanv/BERT-BiLSTM-CRF-NER#188]
![5L%{7H@J6LI@3VW6CS``5B1](https://user-images.githubusercontent.com/35731898/61352913-1bbbbc00-a8a1-11e9-83c9-25b25bf3c91a.png)

**Comment by xiangbei1997** [comment]
老哥,基于包的模式应该如何添加新的实体呢?比如时间?

**Comment by ZhangFisherGit** [comment]
我找了一下。新版的基于源码的训练需要改/bert_base/train/train_helper.py中的参数。然后训练好之后，运行测试的话改terminal_predict.py中的参数后运行就可以了。

**Comment by ZhangFisherGit** [comment]
我找了一下。新版的基于源码的训练需要改/bert_base/train/train_helper.py中的参数。然后训练好之后，运行测试的话改terminal_predict.py中的参数后运行就可以了。

**Comment by ZhangFisherGit** [comment]
> 我找了一下。新版的基于源码的训练需要改/bert_base/train/train_helper.py中的参数。然后训练好之后，运行测试的话改terminal_predict.py中的参数后运行就可以了。

train_helper.py参数改好之后，运行run.py训练模型就行了。然后可以运行terminal_predict.py预测

**Comment by xiangbei1997** [comment]
> 我找了一下。新版的基于源码的训练需要改/bert_base/train/train_helper.py中的参数。然后训练好之后，运行测试的话改terminal_predict.py中的参数后运行就可以了。

多谢,老哥,已经找到了!!!

**Comment by xiangbei1997** [comment]
> > 我找了一下。新版的基于源码的训练需要改/bert_base/train/train_helper.py中的参数。然后训练好之后，运行测试的话改terminal_predict.py中的参数后运行就可以了。
> 
> train_helper.py参数改好之后，运行run.py训练模型就行了。然后可以运行terminal_predict.py预测

老哥,
![2IPI}A}RH043$XA_AK7`8A1](https://user-images.githubusercontent.com/35731898/61758420-4b197e00-adf7-11e9-9735-23faed7a4cca.png)
你解决了没?

**Comment by xiangbei1997** [comment]
> > 我找了一下。新版的基于源码的训练需要改/bert_base/train/train_helper.py中的参数。然后训练好之后，运行测试的话改terminal_predict.py中的参数后运行就可以了。
> 
> train_helper.py参数改好之后，运行run.py训练模型就行了。然后可以运行terminal_predict.py预测

这个问题已经解决了,多谢老哥tf.estimator.experimental.stop_if_no_decrease_hook
