### ISSUE TITLE
关于Dropout_rate

### ISSUE THREAD

**Issue by Vincen1994** [macanv/BERT-BiLSTM-CRF-NER#193]
在读源码时发现Dropout_rate设置的为1或0.9，这明显不合神经网络训练调参常理，后来才发现在有些部分写了keep_prob=self.dropout_rate，然而keep_prob跟dropout_rate实际是两个完全相反的参数，是不是把参数的名称修正一下不要叫dropout_rate而是叫keep_prob更便于大家理解？刚开始看到确实是有点懵逼的。。。只是个建议，非常感谢作者的源码分享，谢谢！

**Comment by macanv** [comment]
bert自身的drop那里，都是使用的默认参数，lstm的drop才会使用dropout_rate吧，谢谢指出。
