### ISSUE TITLE
你可以尝试一下增加这个条件判断解决

### ISSUE THREAD

**Issue by Gingersna** [macanv/BERT-BiLSTM-CRF-NER#2]
https://github.com/macanv/BERT-BiLSMT-CRF-NER/blob/d5054b26aac0a51adbf6f41bb5b0042af28e6b52/bert_lstm_ner.py#L784
关于上面的索引越界的bug，你可以在line 227添加以下条件进行简单分句加以解决
`if len(contends) == 0 and words[-1] in ['。', '？', '！', '.']`
你可以测试一下

**Comment by stevewyl** [comment]
是不是因为prediction的序列长度是固定的 而文本序列的长度可能会超过这个阈值，我增加了这个判断后，就没有越界的问题了

**Comment by OYE93** [comment]
原因应该是https://github.com/macanv/BERT-BiLSTM-CRF-NER/blob/d5054b26aac0a51adbf6f41bb5b0042af28e6b52/bert_lstm_ner.py#L284，序列截断之后，生成的token序列与金标准里的序列是不一样的，长度更短，所以会out of range。

**Comment by macanv** [comment]
感谢~~

**Comment by WaNePr** [comment]
> 是不是因为prediction的序列长度是固定的 而文本序列的长度可能会超过这个阈值，我增加了这个判断后，就没有越界的问题了
@stevewyl 请问你增加了什么条件判断没有出现越界的问题？

**Comment by WaNePr** [comment]
> 原因应该是
> 
> [BERT-BiLSTM-CRF-NER/bert_lstm_ner.py](https://github.com/macanv/BERT-BiLSTM-CRF-NER/blob/d5054b26aac0a51adbf6f41bb5b0042af28e6b52/bert_lstm_ner.py#L284)
> 
> Line 284 in [d5054b2](/macanv/BERT-BiLSTM-CRF-NER/commit/d5054b26aac0a51adbf6f41bb5b0042af28e6b52)
> 
>  if len(tokens) >= max_seq_length - 1: 
> ，序列截断之后，生成的token序列与金标准里的序列是不一样的，长度更短，所以会out of range。

@OYE93 请问您怎么解决这个问题的？

**Comment by OYE93** [comment]
你好，主要原因是test数据里的句子长度是大于max_length的，而作者在处理输入的时候，把句子截断成了max_length，最终predict生成的标注长度也是max_length的，当这个长度小于test数据里的句子长度时，在生成pair对的时候，文本长度大于标注长度，就会报out of range了。  
我的处理是根据标点符号和max_length双重标准把原始的train，Dev，test数据都处理成小于max_length的句子长度，再输入模型，这样既可以充分利用训练数据，也可以得到真实完全的评价。  
当然，我觉得在数据量足够大的情况下，采用直接截断的方式，然后以输出标注为基准生成pair对也是可以的。
