### ISSUE TITLE
请问现在支持用自己的带别的标签的的数据训练吗？

### ISSUE THREAD

**Issue by ZhangFisherGit** [macanv/BERT-BiLSTM-CRF-NER#202]
请问现在可以用自己的带别的标签的的数据训练吗？如果可以，需要更改源代码吗？

**Comment by macanv** [comment]
1. 输入数据和我的一样，不需要改什么
2. 不和我的数据一直，参考https://github.com/macanv/BERT-BiLSTM-CRF-NER/blob/master/bert_base/train/bert_lstm_ner.py的56行数据输入。
