### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'

### ISSUE THREAD

**Issue by zwacm** [macanv/BERT-BiLSTM-CRF-NER#203]
AttributeError: module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'

**Comment by lizhzh8** [comment]
1.12 或1.13版本

**Comment by wangjipeng** [comment]
tf.estimator.experimental.stop_if_no_decrease_hook 试试这个

**Comment by 393301836** [comment]
谢谢，跑conll2003数据集会提示 训练集太小，这是咋回事？
（链接中另外一个中文数据集就不会。）

**Comment by 393301836** [comment]
谢谢，跑conll2003数据集会提示 训练集太小，这是怎么回事？（链接中另外一个中文数据集就不会。）
另外 ， 我已经指定了“chinese_L-12_H-768_A-12”目录， 仍然找不到‘checkpoint’ file。

**Comment by lizhzh8** [comment]
conll2003是因为格式问题吧,你看看源代码train之前的代码,就知道了.中文是用一个空格作为split的

**Comment by 393301836** [comment]
谢谢，果然是TensorFlow版本问题，conll03的格式确实和中文不一致，每一行中有多个空格分隔

**Comment by lcqbit11** [comment]
tf1.15.0可以使用 tf.estimator.experimental.stop_if_no_decrease_hook
