### ISSUE TITLE
text  similarity

### ISSUE THREAD

**Issue by zgd716** [macanv/BERT-BiLSTM-CRF-NER#209]
使用bert  service部署文本相似度模型的话，应该修改哪些地方？

**Comment by macanv** [comment]
模型压缩以及通信模块中的输入输出。

**Comment by zgd716** [comment]
你好，server端代码调试完了，但是使用pb直接预测的概率和使用server提供的pb预测 概率结果完全不一样，大佬，有思路哪一块逻辑出问题了吗？

**Comment by macanv** [comment]
没明白，是两个结果概率对比的。

**Comment by zgd716** [comment]
> 没明白，是两个结果概率对比的。

已解决，多谢大佬

**Comment by kyrieCc** [comment]
请教大佬怎么部署的文本相似模型？万分感谢！
需要自己修改bert-service文件吗>
