### ISSUE TITLE
模型收敛情况

### ISSUE THREAD

**Issue by luoyexuge** [macanv/BERT-BiLSTM-CRF-NER#21]
问下各位，这模型训练到多少个echo开始收敛，损失函数在train上多大，最近我在上千万数据上做ner，模型一直不收敛，所有的数据都过一遍不见收敛，求交流？

**Comment by macanv** [comment]
你这个上千万是token上千万，，还是seq上千万啊。我的数据(200M文本)都收敛了，如果还是不收敛，我建议你检查一下你的数据，或者看下base 方法work 不？

**Comment by luoyexuge** [comment]
多谢各位，我学习率设置有点大，导致没法收敛。。。
