### ISSUE TITLE
用自己的新的实体标签 预测得到准确率特别低 预测结果中出现B-和I-不配套的情况

### ISSUE THREAD

**Issue by xmy7216** [macanv/BERT-BiLSTM-CRF-NER#214]
1、数据集不大，只有4000+条句子
2、labels.txt的内容为
![image](https://user-images.githubusercontent.com/31274050/63006026-40ab4b00-beb0-11e9-9a09-ac42044f7dde.png)
不知道这里面是不是必须加上"X", “[CLS]”, “[SEP]”
3、运行命令如下
![image](https://user-images.githubusercontent.com/31274050/63006148-849e5000-beb0-11e9-822a-039ccdfee32c.png)
4、测试集上效果很差
![image](https://user-images.githubusercontent.com/31274050/63006269-bf07ed00-beb0-11e9-974d-5adbf8cace14.png)
5、查看label_test.txt，发现问题
![image](https://user-images.githubusercontent.com/31274050/63006409-127a3b00-beb1-11e9-81b6-ae7a6e1251f9.png)
![image](https://user-images.githubusercontent.com/31274050/63006482-3c336200-beb1-11e9-9936-ffab20e108af.png)
![image](https://user-images.githubusercontent.com/31274050/63006561-638a2f00-beb1-11e9-9388-62116daaa9e8.png)
![image](https://user-images.githubusercontent.com/31274050/63006609-7bfa4980-beb1-11e9-9743-25c4e78c3983.png)

不知道这种状况是什么原因导致的，谢谢

**Comment by wbj0110** [comment]
我也遇到这个问题，句子开始应该只能为O或者B-怎么会有I-开头的，CRF模板不对吗

**Comment by xmy7216** [comment]
> 我也遇到这个问题，句子开始应该只能为O或者B-怎么会有I-开头的，CRF模板不对吗

不知道，还没找到原因，感觉预测结果都是乱的

**Comment by GDongLin** [comment]
你们找到原因了吗？我也是出现了这个问题，我一度以为是我代码改错了...

**Comment by mingxixixi** [comment]
你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？

**Comment by xmy7216** [comment]
检查一下数据标注有没有出错，然后可以尝试一下把数据集扩大然后训练试试！

**Comment by xmy7216** [comment]
> 你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？


> 你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？

可以找找作者训练好的模型，然后只预测就好了应该

**Comment by mingxixixi** [comment]
> > 你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？
> 
> > 你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？
> 
> 可以找找作者训练好的模型，然后只预测就好了应该

好的，谢谢，这个是不是需要修改代码

**Comment by xmy7216** [comment]
> > > 你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？
> > 
> > 
> > > 你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？
> > 
> > 
> > 可以找找作者训练好的模型，然后只预测就好了应该
> 
> 好的，谢谢，这个是不是需要修改代码

如果只是用他的模型 可以不用修改代码

**Comment by mingxixixi** [comment]
> > > > 你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？
> > > 
> > > 
> > > > 你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？
> > > 
> > > 
> > > 可以找找作者训练好的模型，然后只预测就好了应该
> > 
> > 
> > 好的，谢谢，这个是不是需要修改代码
> 
> 如果只是用他的模型 可以不用修改代码

嗯嗯，谢谢你了

**Comment by mingxixixi** [comment]
> > > > 你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？
> > > 
> > > 
> > > > 你好，我现在的数据没有标注，所以想利用这个现有的模型给我的数据打一下标签，这个应该怎么弄呢？
> > > 
> > > 
> > > 可以找找作者训练好的模型，然后只预测就好了应该
> > 
> > 
> > 好的，谢谢，这个是不是需要修改代码
> 
> 如果只是用他的模型 可以不用修改代码

你好，请问你有用过作者的模型吗，现在好像下载不了了？

**Comment by mingxixixi** [comment]
> 1、数据集不大，只有4000+条句子
> 2、labels.txt的内容为
> ![image](https://user-images.githubusercontent.com/31274050/63006026-40ab4b00-beb0-11e9-9a09-ac42044f7dde.png)
> 不知道这里面是不是必须加上"X", “[CLS]”, “[SEP]”
> 3、运行命令如下
> ![image](https://user-images.githubusercontent.com/31274050/63006148-849e5000-beb0-11e9-822a-039ccdfee32c.png)
> 4、测试集上效果很差
> ![image](https://user-images.githubusercontent.com/31274050/63006269-bf07ed00-beb0-11e9-974d-5adbf8cace14.png)
> 5、查看label_test.txt，发现问题
> ![image](https://user-images.githubusercontent.com/31274050/63006409-127a3b00-beb1-11e9-81b6-ae7a6e1251f9.png)
> ![image](https://user-images.githubusercontent.com/31274050/63006482-3c336200-beb1-11e9-9936-ffab20e108af.png)
> ![image](https://user-images.githubusercontent.com/31274050/63006561-638a2f00-beb1-11e9-9388-62116daaa9e8.png)
> ![image](https://user-images.githubusercontent.com/31274050/63006609-7bfa4980-beb1-11e9-9743-25c4e78c3983.png)
> 
> 不知道这种状况是什么原因导致的，谢谢

你好，如何能让预测数据的输出格式变成你上面那样子呢？

**Comment by xmy7216** [comment]
> > 1、数据集不大，只有4000+条句子
> > 2、labels.txt的内容为
> > ![image](https://user-images.githubusercontent.com/31274050/63006026-40ab4b00-beb0-11e9-9a09-ac42044f7dde.png)
> > 不知道这里面是不是必须加上"X", “[CLS]”, “[SEP]”
> > 3、运行命令如下
> > ![image](https://user-images.githubusercontent.com/31274050/63006148-849e5000-beb0-11e9-822a-039ccdfee32c.png)
> > 4、测试集上效果很差
> > ![image](https://user-images.githubusercontent.com/31274050/63006269-bf07ed00-beb0-11e9-974d-5adbf8cace14.png)
> > 5、查看label_test.txt，发现问题
> > ![image](https://user-images.githubusercontent.com/31274050/63006409-127a3b00-beb1-11e9-81b6-ae7a6e1251f9.png)
> > ![image](https://user-images.githubusercontent.com/31274050/63006482-3c336200-beb1-11e9-9936-ffab20e108af.png)
> > ![image](https://user-images.githubusercontent.com/31274050/63006561-638a2f00-beb1-11e9-9388-62116daaa9e8.png)
> > ![image](https://user-images.githubusercontent.com/31274050/63006609-7bfa4980-beb1-11e9-9743-25c4e78c3983.png)
> > 不知道这种状况是什么原因导致的，谢谢
> 
> 你好，如何能让预测数据的输出格式变成你上面

> > 1、数据集不大，只有4000+条句子
> > 2、labels.txt的内容为
> > ![image](https://user-images.githubusercontent.com/31274050/63006026-40ab4b00-beb0-11e9-9a09-ac42044f7dde.png)
> > 不知道这里面是不是必须加上"X", “[CLS]”, “[SEP]”
> > 3、运行命令如下
> > ![image](https://user-images.githubusercontent.com/31274050/63006148-849e5000-beb0-11e9-822a-039ccdfee32c.png)
> > 4、测试集上效果很差
> > ![image](https://user-images.githubusercontent.com/31274050/63006269-bf07ed00-beb0-11e9-974d-5adbf8cace14.png)
> > 5、查看label_test.txt，发现问题
> > ![image](https://user-images.githubusercontent.com/31274050/63006409-127a3b00-beb1-11e9-81b6-ae7a6e1251f9.png)
> > ![image](https://user-images.githubusercontent.com/31274050/63006482-3c336200-beb1-11e9-9936-ffab20e108af.png)
> > ![image](https://user-images.githubusercontent.com/31274050/63006561-638a2f00-beb1-11e9-9388-62116daaa9e8.png)
> > ![image](https://user-images.githubusercontent.com/31274050/63006609-7bfa4980-beb1-11e9-9743-25c4e78c3983.png)
> > 不知道这种状况是什么原因导致的，谢谢
> 
> 你好，如何能让预测数据的输出格式变成你上面那样子呢？

运行代码后，在output文件夹里会自动生成label_test.txt

**Comment by mingxixixi** [comment]
> > > 1、数据集不大，只有4000+条句子
> > > 2、labels.txt的内容为
> > > ![image](https://user-images.githubusercontent.com/31274050/63006026-40ab4b00-beb0-11e9-9a09-ac42044f7dde.png)
> > > 不知道这里面是不是必须加上"X", “[CLS]”, “[SEP]”
> > > 3、运行命令如下
> > > ![image](https://user-images.githubusercontent.com/31274050/63006148-849e5000-beb0-11e9-822a-039ccdfee32c.png)
> > > 4、测试集上效果很差
> > > ![image](https://user-images.githubusercontent.com/31274050/63006269-bf07ed00-beb0-11e9-974d-5adbf8cace14.png)
> > > 5、查看label_test.txt，发现问题
> > > ![image](https://user-images.githubusercontent.com/31274050/63006409-127a3b00-beb1-11e9-81b6-ae7a6e1251f9.png)
> > > ![image](https://user-images.githubusercontent.com/31274050/63006482-3c336200-beb1-11e9-9936-ffab20e108af.png)
> > > ![image](https://user-images.githubusercontent.com/31274050/63006561-638a2f00-beb1-11e9-9388-62116daaa9e8.png)
> > > ![image](https://user-images.githubusercontent.com/31274050/63006609-7bfa4980-beb1-11e9-9743-25c4e78c3983.png)
> > > 不知道这种状况是什么原因导致的，谢谢
> > 
> > 
> > 你好，如何能让预测数据的输出格式变成你上面
> 
> > > 1、数据集不大，只有4000+条句子
> > > 2、labels.txt的内容为
> > > ![image](https://user-images.githubusercontent.com/31274050/63006026-40ab4b00-beb0-11e9-9a09-ac42044f7dde.png)
> > > 不知道这里面是不是必须加上"X", “[CLS]”, “[SEP]”
> > > 3、运行命令如下
> > > ![image](https://user-images.githubusercontent.com/31274050/63006148-849e5000-beb0-11e9-822a-039ccdfee32c.png)
> > > 4、测试集上效果很差
> > > ![image](https://user-images.githubusercontent.com/31274050/63006269-bf07ed00-beb0-11e9-974d-5adbf8cace14.png)
> > > 5、查看label_test.txt，发现问题
> > > ![image](https://user-images.githubusercontent.com/31274050/63006409-127a3b00-beb1-11e9-81b6-ae7a6e1251f9.png)
> > > ![image](https://user-images.githubusercontent.com/31274050/63006482-3c336200-beb1-11e9-9936-ffab20e108af.png)
> > > ![image](https://user-images.githubusercontent.com/31274050/63006561-638a2f00-beb1-11e9-9388-62116daaa9e8.png)
> > > ![image](https://user-images.githubusercontent.com/31274050/63006609-7bfa4980-beb1-11e9-9743-25c4e78c3983.png)
> > > 不知道这种状况是什么原因导致的，谢谢
> > 
> > 
> > 你好，如何能让预测数据的输出格式变成你上面那样子呢？
> 
> 运行代码后，在output文件夹里会自动生成label_test.txt

嗯嗯，你有用过作者的模型吗，可不可以给分享一个

**Comment by xmy7216** [comment]
> 
> 嗯嗯，你有用过作者的模型吗，可不可以给分享一个

我是训练自己的数据，新标签，没有作者训练好的模型

**Comment by mingxixixi** [comment]
嗯嗯，行，谢谢你啦！

**Comment by mingxixixi** [comment]
> > 嗯嗯，你有用过作者的模型吗，可不可以给分享一个
> 
> 我是训练自己的数据，新标签，没有作者训练好的模型

嗯嗯，行，谢谢你啦！
