### ISSUE TITLE
不知道大佬还有没有训练好的模型？

### ISSUE THREAD

**Issue by fycm123** [macanv/BERT-BiLSTM-CRF-NER#215]
自己机器训练速度太慢，可以再分享一下训练好的模型吗，十分感谢

**Comment by macanv** [comment]
你想要啥模型，哈哈

**Comment by fycm123** [comment]
就是用预训练模型训练之后的中文命名实体识别模型，有的话可以发我一份吗，谢谢！




------------------ 原始邮件 ------------------
发件人: "MaCan"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 上午8:29
收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com>;
抄送: "LAGERY"<601377318@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [macanv/BERT-BiLSTM-CRF-NER] 不知道大佬还有没有训练好的模型？ (#215)




你想要啥模型，哈哈

**Comment by macanv** [comment]
readme有。
