### ISSUE TITLE
你好，文本分类模型提供服务如何输出多个标签的结果

### ISSUE THREAD

**Issue by cy576013581** [macanv/BERT-BiLSTM-CRF-NER#218]
目前文本分类模型接口中只有1个标签以及其概率，如果需要多个，怎么处理

**Comment by macanv** [comment]
多个是指啥？  多标签分类中的多标签还是模型softmax 后的概率分布？

**Comment by cy576013581** [comment]
softmax 后的概率分布，我改了下接口之后可以了，麻烦了

**Comment by LeoWood** [comment]
> softmax 后的概率分布，我改了下接口之后可以了，麻烦了

你好，我也想问这个问题，请问是如何修改的呢？
