### ISSUE TITLE
预测结果，没有看到利用trans 进行viterbi解码问题

### ISSUE THREAD

**Issue by JNUpython** [macanv/BERT-BiLSTM-CRF-NER#219]
hello，我训练确实得到比较理想的预测结果，result = estimator.predict(input_fn=predict_input_fn)里面如何得到结果了，没有看到维特比解码过程？这是如何实现的了？

**Comment by macanv** [comment]
estimator  在创建的时候已经定义了model_fn, so,每次predict的时候，自然会去调用该函数，然后传入的mode参数 是tf.estimator.ModenKey.PREDICT（可能拼写有错），看下model_fn 基本就能明白吧。

**Comment by JNUpython** [comment]
谢谢，解答！已经看到并理解，真棒



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MaCan <notifications@github.com&gt;
发送时间: 2019年9月21日 09:02
收件人: macanv/BERT-BiLSTM-CRF-NER <BERT-BiLSTM-CRF-NER@noreply.github.com&gt;
抄送: kean_lee <609219732@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[macanv/BERT-BiLSTM-CRF-NER] 预测结果，没有看到利用trans 进行viterbi解码问题 (#219)




estimator  在创建的时候已经定义了model_fn, so,每次predict的时候，自然会去调用该函数，然后传入的mode参数 是tf.estimator.ModenKey.PREDICT（可能拼写有错），看下model_fn 基本就能明白吧。
