### ISSUE TITLE
用自己的数据集跑出来的结果不是很好

### ISSUE THREAD

**Issue by swy0915** [macanv/BERT-BiLSTM-CRF-NER#22]
用默认给的数据集跑出来效果
![qq 20181221151942](https://user-images.githubusercontent.com/16319211/50329861-e1b95000-0533-11e9-8f1c-ee065cf1658b.png)
用自己的数据集跑出来的结果不是很好，
![qq 20181221151855](https://user-images.githubusercontent.com/16319211/50329815-c3ebeb00-0533-11e9-8767-c59e19a1b866.png)
为什么？有人和我一样吗？

**Comment by Kuzzzz** [comment]
> 还有 数据里会有如图形式的判定,但是加了crf理论上这样的情况应该很少很少,但是数据里有不少这样单个I开头的
> ![qq 20181221152833](https://user-images.githubusercontent.com/16319211/50330137-1da0e500-0535-11e9-859b-2a4037ecb002.png)

请问你是在什么GPU上进行训练的？

**Comment by macanv** [comment]
check一下你的数据是不是超过了128导致实际输入会出现l开头的，使用data-process 先处理一下吧，其次，数据很大的时候，建议epoch 设置大一点

我的GPU 
是p40 24G

**Comment by macanv** [comment]
@Kuzzzz 这个是在预测的时候，predict的地方有bug，现在基本不会出现这样的，因为你的输入有个token在bert的vocab.txt中不存在。。。

**Comment by fengchi863** [comment]
请问你的数据集格式是怎么定义的？按照ConLL2003那样么？这个格式有哪些要注意的地方？

**Comment by yflfly** [comment]
想问一下，这个问题解决了吗？

**Comment by yflfly** [comment]
![image](https://user-images.githubusercontent.com/16858340/62990282-f90bcb80-be7d-11e9-9c33-939885288174.png)
 输入同样的一个句子，句子末尾加上句号和不加上句号测试出的结果会出现标签错误的情况
