### ISSUE TITLE
怎么训练？

### ISSUE THREAD

**Issue by Lanme** [macanv/BERT-BiLSTM-CRF-NER#225]
恕我没看明白怎么训练的
  python3 bert_lstm_ner.py   \
                  --task_name="NER"  \ 
                  --do_train=True   \
                  --do_eval=True   \
                  --do_predict=True
                  --data_dir=NERdata   \
                  --vocab_file=checkpoint/vocab.txt  \ 
                  --bert_config_file=checkpoint/bert_config.json \  
                  --init_checkpoint=checkpoint/bert_model.ckpt   \
                  --max_seq_length=128   \
                  --train_batch_size=32   \
                  --learning_rate=2e-5   \
                  --num_train_epochs=3.0   \
                  --output_dir=./output/result_dir/ 
这个是cd到bert_base/train 文件夹下的bert_lstm_ner.py下训练的么？那里没有跑的__main__函数之类的代码呀？同理450行也找不到你说的crf_only的代码。新版本用的以下命令：
bert-base-ner-train \
    -data_dir nerdata\
    -output_dir output\
    -init_checkpoint checkpoint/bert_model.ckpt\
    -bert_config_file checkpoint/bert_config.json\
    -vocab_file checkpoint/vocab.txt
然后我就一直卡在训练中间过程，没有打印任何信息，五分钟后的记录：
![image](https://user-images.githubusercontent.com/28859589/63658992-5b02f400-c7e1-11e9-82fa-3438996db60e.png)

**Comment by macanv** [comment]
因为log的原因，训练的时候，不能输出信息，训练结束会显示一些信息，多等一下，再看看吧。
