### ISSUE TITLE
请教，预测时候，输入一句话，还需要处理成句首加[CLS], 句尾加[SEP]的形式吗，因为server的代码好多，没看懂，特来请教下

### ISSUE THREAD

**Issue by dh12306** [macanv/BERT-BiLSTM-CRF-NER#226]
如题， @macanv ，谢谢大神

**Comment by macanv** [comment]
如果使用bertClient的话，不需要了，可以看下client_test.py

**Comment by xmy7216** [comment]
> 如果使用bertClient的话，不需要了，可以看下client_test.py
请问terminal_predict.py的302行这个判断if tag[0] == "S":是在判断这个tag是不是SEP？但是句尾标识不是[SEP]吗？没看太懂，求解答
https://github.com/macanv/BERT-BiLSTM-CRF-NER/blob/master/terminal_predict.py#L302

**Comment by macanv** [comment]
反正就是不需要了，这里不是输入的处理。

**Comment by lizhzh8** [comment]
求教 @macanv  大神：
terminal_predict.py 这个基于命名行的预测程序，现在还能用吗？标准案例预测出来的结果不太对。我用bertClient客户端访问server的方式能够准确预测。terminal_predict.py需要进行修改吗？

sentence = "国务院总理李克强在雄安新区召开会议"
用bertClient预测结果如下：
```
(dlpy36) [root@localhost BERT-BiLSTM-CRF-NER-master]# python client_test.py 
rst: [['B-ORG' 'I-ORG' 'I-ORG' 'O' 'O' 'B-PER' 'I-PER' 'I-PER' 'O' 'B-LOC'
  'I-LOC' 'I-LOC' 'I-LOC' 'O' 'O' 'O' 'O' 'O']]

```

但是用terminal_predict.py预测的结果不对，具体结果如下：
```
input the test sentence:
国务院总理李克强在雄安新区召开会议
2019-08-29 13:53:53.709574: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
[['X', 'B-PER', 'I-ORG', 'I-ORG', 'I-PER', 'I-PER', 'I-PER', 'B-ORG', 'I-LOC', 'I-LOC', 'I-LOC', 'I-PER', 'I-PER', 'I-PER', 'I-PER', 'B-LOC']]
LOC, 会
PER, 务院总理李克, 强在雄安新区召开
ORG
time used: 0.538042 sec
```

**Comment by macanv** [comment]
不保证能用。具体逻辑看自己的任务吧。

**Comment by lizhzh8** [comment]
> 不保证能用。具体逻辑看自己的任务吧。

嗯嗯，我找到问题了。谢谢大神。我训练的模型有点问题

**Comment by smallduckpro** [comment]
@lizhzh8 你好，我遇到了和你一样的情况，方便说明一下是什么问题吗？感谢！
