### ISSUE TITLE
起BERT服务出错

### ISSUE THREAD

**Issue by flytoylf** [macanv/BERT-BiLSTM-CRF-NER#235]
![image](https://user-images.githubusercontent.com/29849325/64672906-628ff180-d49f-11e9-948a-5591fa9562b1.png)

![image](https://user-images.githubusercontent.com/29849325/64672931-6de31d00-d49f-11e9-8424-e6022ddf15c1.png)

**Comment by macanv** [comment]
如果只是单纯的想起bert,可以直接使用bert as service,那个更稳定。
