### ISSUE TITLE
BERT+CRF的服务耗时问题

### ISSUE THREAD

**Issue by flytoylf** [macanv/BERT-BiLSTM-CRF-NER#236]
搭建了一个BERT+CRF的服务，测了一下大概是50ms，输入的长度是10个汉字，感觉耗时有点高，正常单独bert的耗时大约在10~20ms，请问这是什么问题？

**Comment by macanv** [comment]
crf解码需要时间啊

**Comment by macanv** [comment]
增加lstm,将crf的输入纬度降低，能一定的减少CRF的解码时间
