### ISSUE TITLE
分类模式运bert-base-serving-start，生成pb文件错误

### ISSUE THREAD

**Issue by shcrkj** [macanv/BERT-BiLSTM-CRF-NER#237]
用自己训练的分类模型，分类模式运行bert-base-serving-start，未能生成pb文件并报错，num_labels为0，修改了server/_init_.py，在第656行后加num_labels = len(label2id)，可以正常运行，不知道这是不是个bug

**Comment by macanv** [comment]
bert-base-serving-start 完整参数发一下？

**Comment by macanv** [comment]
参考一下新上传的thu_classification.py，我是使用这个文件训练的文本分类，代码会生成label2id.pkl 和label_list.pkl两个文件，在起服务的时候，服务会自动加载。
