### ISSUE TITLE
输入序列与预测序列长度不一

### ISSUE THREAD

**Issue by Machine-Tom** [macanv/BERT-BiLSTM-CRF-NER#247]
发现了一个很奇怪的问题，
输入序列为：
《XXX》，为了保障XXX
预测序列为：
2 2 5 5 5 5 5 5 5 5 5 0 5 
中间因为出现0，按照程序思路，0为“mask”。为什么会在5之前提前出现mask？

**Comment by macanv** [comment]
输出一下tokenizer 的输出结果。
