### ISSUE TITLE
Raise Attribute error 'training data is so small'

### ISSUE THREAD

**Issue by zjsuper** [macanv/BERT-BiLSTM-CRF-NER#249]
I'm trying to run 
`
bert-base-ner-train \
    -data_dir {your dataset dir}\
    -output_dir {training output dir}\
    -init_checkpoint {Google BERT model dir}\
    -bert_config_file {bert_config.json under the Google BERT model dir} \
    -vocab_file {vocab.txt under the Google BERT model dir}
`
And got the error Raise Attribute error 'training data is so small'

I used my own data in English. I have about 25,000 lines in training data,  the batch size is 64, epoch is 10, so (25000/64*10) should be larger than 1

Does anyone know why this happen? Thanks very much

**Comment by macanv** [comment]
check your input data format, make sure your data format are the same witg my readme file

**Comment by macanv** [comment]
Refusing to speak to Americans in Houston。 HK belongs to china!!!
