### ISSUE TITLE
重复操作

### ISSUE THREAD

**Issue by newwaylw** [macanv/BERT-BiLSTM-CRF-NER#25]
https://github.com/macanv/BERT-BiLSTM-CRF-NER/blob/4c7c7f7e530ee8f5b8d9b80b38ff4dbf8e4176fe/bert_lstm_ner.py#L264

可以在方法外建立一个label_map, 然后作为参数传入，不需要对每个example都从label_list开始创建一个label_id map.

**Comment by macanv** [comment]
label2id 这个map是如果有就不会创建，所以在训练阶段就会创建，
