### ISSUE TITLE
为什么0号卡显存占用那么高，而2、3号却很低

### ISSUE THREAD

**Issue by shen865069799** [macanv/BERT-BiLSTM-CRF-NER#251]
![显存](https://user-images.githubusercontent.com/31476124/66548625-36d25b00-eb74-11e9-8001-02ab8a430d56.PNG)

**Comment by macanv** [comment]
因为只用了一个卡训练啊

**Comment by shen865069799** [comment]
> 因为只用了一个卡训练啊

group2.add_argument('-device_map', type=str, default='0,1,2',
                        help='witch device using to train')这里设置0,1,2不起作用？
