### ISSUE TITLE
改进

### ISSUE THREAD

**Issue by yinjuncheng** [macanv/BERT-BiLSTM-CRF-NER#255]
请问如果用这个模型来做中文的实体识别比赛，有那些方面可以改进一下呢？（能分享一下大致的方向就好

**Comment by macanv** [comment]
很少打比赛，基于BERT的效果提升，从论文上来看，可以进行pretrain 然后在训练模型，贴合数据和任务的pretrain效果能有一定的提升，pretrain的时候，注意你的切词方法，OOV处理方法，任务和数据有什么特别的地方进行。还有就是换其他的预训练模型试试，比如albert等，最后，**good luck** ！
