### ISSUE TITLE
英文预测标签中含X

### ISSUE THREAD

**Issue by littletomato** [macanv/BERT-BiLSTM-CRF-NER#256]
如题，用bert英文在英文数据集上训练，最后标签中含有X怎么解决？有大佬知道吗？
![image](https://user-images.githubusercontent.com/10340566/67256542-2dbd8400-f4ba-11e9-940d-8deff418f2d2.png)

**Comment by macanv** [comment]
X只是一个符号罢了，你改一下代码不就OK了？

**Comment by littletomato** [comment]
是把标签X去掉吗？
然后把bert_lstm_ner.py中的
![image](https://user-images.githubusercontent.com/10340566/67375948-eae0d680-f5b5-11e9-9a8d-688778a33b09.png)
改成
![image](https://user-images.githubusercontent.com/10340566/67376135-372c1680-f5b6-11e9-9a6e-1c8692b7f9a8.png)
这样吗？

**Comment by macanv** [comment]
X是用来做wordpice的时候，切分问题添加的label，这样改一版也不会出现什么问题，不过不是很推荐，你可以把X改成任意一个你数据集里没有的符号例如XX。然后，在label set处，做相应修改即可。
