### ISSUE TITLE
模型训练多少轮才会输出P、R、F值呀？？loss值也没有显示，有点不太明白

### ISSUE THREAD

**Issue by henryhust** [macanv/BERT-BiLSTM-CRF-NER#258]
项目每次仅输出
shape of input_ids (?, 202)
I:NER Training:[ber:mod:371]:*** Features ***
I:NER Training:[ber:mod:373]:  name = input_ids, shape = (?, 202)
I:NER Training:[ber:mod:373]:  name = input_mask, shape = (?, 202)
I:NER Training:[ber:mod:373]:  name = label_ids, shape = (?, 202)
I:NER Training:[ber:mod:373]:  name = segment_ids, shape = (?, 202)
没有输出其他的测试指标和loss值，大概多少轮才能生成？如何设置每轮进行一次输出，感谢！

**Comment by henryhust** [comment]
我把数据从14M降到5M之后，一轮就直接输出结果了，大数据量文本持续输出测试指标如何进行修改呢？

**Comment by macanv** [comment]
自己修改log, 如果想看，可以把log全部关掉，则就会只输出tf默认输出。
