### ISSUE TITLE
缺少label_list.pkl

### ISSUE THREAD

**Issue by Jerryten** [macanv/BERT-BiLSTM-CRF-NER#26]
Errno 2] No such file or directory: 'F:\\BERT-BiLSTM-CRF-NER-master\\output\\label_list.pkl'
是在运行bert_lstm_ner.py的时候发生的

**Comment by yzho0907** [comment]
plz create a output folder under the BERT-BiLSTM-CRF-NER-maste.

**Comment by Jerryten** [comment]
添加了output文件夹后出现的问题
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\BERT-BiLSTM-CRF-NER-master\\output\\label2id.pkl'

**Comment by yzho0907** [comment]
@Jerryten try Linux, or solve path problems by your own before u use this code in windows

**Comment by macanv** [comment]
@Jerryten  你看下你训练后的数据label2id.pkl 在哪里。。。这个bug应该已经修复了

**Comment by fengchaozheng120** [comment]
mkdir output
