### ISSUE TITLE
用英文BERT训练成功，run terminal_predict failed

### ISSUE THREAD

**Issue by zhengcongyin** [macanv/BERT-BiLSTM-CRF-NER#260]
Error message: 
W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key bert/encoder/layer_12/attention/output/LayerNorm/beta not found in checkpoint

**Comment by Crystalsudo** [comment]
遇到了这个问题，请教您这边是怎么解决的？

**Comment by ChenLeeStu** [comment]
我想请教一下，用英文需要改变哪些？我自己跑出来的效果很差。
