### ISSUE TITLE
好像没有使用GPU运行

### ISSUE THREAD

**Issue by caseware66** [macanv/BERT-BiLSTM-CRF-NER#262]
![image](https://user-images.githubusercontent.com/25001446/68082281-b989c580-fe55-11e9-8436-386bdb3aaf0c.png)

**Comment by caseware66** [comment]
麻烦各位专家给看一下怎么回事？

**Comment by macanv** [comment]
jupyter 是什么鬼？

**Comment by caseware66** [comment]
您好，
&nbsp; &nbsp; &nbsp; &nbsp; 我之前的问题已经解决，目前有一个新的问题，就是我在用http 请求的时候，请求并发数设置为500个，一旦某个连接报错了，该连接就不能用了，最后500个连接都不能用了，最后显示的错误是 RuntimeError: Too many concurrent connections!Try to increase the value of "max_concurrency", currently =500
。但是我用client_test.py请求该服务器上的server是可以请求成功。望您给指导一下。


附件是我的log日志。













陈稀
----------------------------------------
数联道（北京）科技有限公司
手机：18618487805
邮箱：157500647@qq.com
传真：010-65566855


&nbsp;




------------------ 原始邮件 ------------------
发件人:&nbsp;"MaCan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 上午10:13
收件人:&nbsp;"macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com&gt;;
抄送:&nbsp;"泡沫"<157500647@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [macanv/BERT-BiLSTM-CRF-NER] 好像没有使用GPU运行 (#262)




Closed #262.
