### ISSUE TITLE
请问使用tensorflow-gpu 什么版本，CUDA和cudnn对应什么版本

### ISSUE THREAD

**Issue by caseware66** [macanv/BERT-BiLSTM-CRF-NER#263]
目前安装tensorflow 1.13.0  cuda 10.1，cudnn7.6 GPU利用率为0，cpu爆满，模型运行超慢，找不到原因

**Comment by macanv** [comment]
tensorflow-gpu吧， 其他任务也是不会自动到GPU么？

**Comment by ChChwang** [comment]
哪个版本呢
