### ISSUE TITLE
job生成后没有返回结果

### ISSUE THREAD

**Issue by blankxyz** [macanv/BERT-BiLSTM-CRF-NER#267]
你好，我使用的是您预训练的分类模型。
text classification model from: https://pan.baidu.com/s/1oFPsOUh1n5AM2HjDIo2XCw, ex_code: bbu8

执行后得到

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 384 values, but the requested shape has 606

**Comment by macanv** [comment]
输入参数维度有问题，自己check一下吧。
