### ISSUE TITLE
f1值为0

### ISSUE THREAD

**Issue by ademolyk** [macanv/BERT-BiLSTM-CRF-NER#268]
您好，ner任务，更改了标签，训练过程无异常，训练完后precision,recall, f1值都为0，烦请有时间看一哈

**Comment by ademolyk** [comment]
![1684A36B0B2F071D4DD2666EE1D8A986](https://user-images.githubusercontent.com/42731232/69139678-f7484880-0afb-11ea-966f-d4f480225e2f.jpg)

**Comment by ademolyk** [comment]
@macanv 类似于这种。麻烦dalao了

**Comment by ademolyk** [comment]
已解决，可能是参数原因吧， 我用5个epoch跑就是全部是0，30个epoch跑，在90%左右基于实体标注的数量。

**Comment by qzd147** [comment]
楼主你好，我也遇到了这个问题，用自己的数据跑完结果全是0，用的是10个epoch，增加epoch次数真的可以吗？
