### ISSUE TITLE
ner_model_dir无效问题

### ISSUE THREAD

**Issue by CACppuccino** [macanv/BERT-BiLSTM-CRF-NER#274]
在mac上使用的tensorflow 1.12.3版本，git clone下的代码并使用setup.py install 来安装的bert_base，但仍然有arg无法识别的问题

**Comment by CACppuccino** [comment]
建议更新一下README里的sample以及CSDN的文档

**Comment by macanv** [comment]
谢谢，工作以后，就没机器弄了，有时间会好好整理。

**Comment by CACppuccino** [comment]
已解决：需要把ner_model_dir改为model_dir即可
