### ISSUE TITLE
自己数据训练好NER模型后，压缩ckpt模型为pb格式，Key output_bias not found in checkpoint

### ISSUE THREAD

**Issue by quewentian** [macanv/BERT-BiLSTM-CRF-NER#292]
使用自己的数据用run.py训练NER模型，之后想部署服务，压缩ckpt为pb格式，却一直提示这个错误，还请大佬赐教~感谢！

Key output_bias not found in checkpoint
         [[node save/RestoreV2 (defined at freeze_graph.py:191)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by macanv** [comment]
模型加载错了。我写了两个示例在代码里了。
