### ISSUE TITLE
句子对相似度计算模型的部署

### ISSUE THREAD

**Issue by Vincent131499** [macanv/BERT-BiLSTM-CRF-NER#294]
请问针对句子对相似度计算的模型，如何部署呢？敬请回复！

**Comment by macanv** [comment]
参考https://github.com/macanv/BERT-BiLSTM-CRF-NER/blob/master/bert_base/server/simple_flask_http_service.py

**Comment by Vincent131499** [comment]
Thanks for your reply, I have implemented this feature now
