### ISSUE TITLE
预测时dropout设置问题

### ISSUE THREAD

**Issue by Gang-Yang** [macanv/BERT-BiLSTM-CRF-NER#295]
在lstm_crf_layer.py文件中，通过变量is_training控制dropout，但是我发现is_training只能控制embedding的dropout，并没有控制rnn的dropout。按理来说预测时rnn的dropout也应该置为1.
不知道这里是不是有点问题。

**Comment by macanv** [comment]
是的，但是在测试的时候，输入的dropout_rate是1
