### ISSUE TITLE
服务调用限制

### ISSUE THREAD

**Issue by yuxuan2015** [macanv/BERT-BiLSTM-CRF-NER#298]
@macanv 
为什么服务调用超过一定的次数之后，我在自己的电脑上测的当调用超过14352次后，服务就不能正常获得结果了？
返回结果如下：
{'description': 'Too many concurrent connections!Try to increase the value of "max_concurrency", currently =10', 'status': 400, 'type': 'RuntimeError'}
我试过在起服务之前把max_concurrency改成50，到41000多的时候，又会出现上面的情况；甚至调到500，到一定程度也会出现上述情况；

**Comment by macanv** [comment]
应该是service 出错，建议不要使用这个service，自己封装服务

**Comment by macanv** [comment]
在server下新增了flask的服务方法，可以试一下。

**Comment by caseware66** [comment]
> 在server下新增了flask的服务方法，可以试一下。

您好我使用flask服务后，怎么能更好的利用GPU并行推理呢。
