### ISSUE TITLE
未做任何调整，连续两次跑的结果，为什么差别那么大呢？

### ISSUE THREAD

**Issue by a461925358** [macanv/BERT-BiLSTM-CRF-NER#299]
未做任何调整，连续两次跑的结果，为什么差别那么大呢？会出现有的类别实体提取不到

processed 32954 tokens with 864 phrases; found: 867 phrases; correct: 862.
accuracy:  99.64%; precision:  99.42%; recall:  99.77%; FB1:  99.60
              COM: precision:  99.39%; recall:  99.69%; FB1:  99.54  652
              FUN: precision: 100.00%; recall: 100.00%; FB1: 100.00  101
              PER: precision:  99.12%; recall: 100.00%; FB1:  99.56  114

-----------------------------------------------------------------------------------------------------------
processed 32954 tokens with 864 phrases; found: 963 phrases; correct: 762.
accuracy:  99.65%; precision:  79.13%; recall:  88.19%; FB1:  83.42
              COM: precision:  86.42%; recall:  99.85%; FB1:  92.65  751
              FUN: precision:   0.00%; recall:   0.00%; FB1:   0.00  99
              PER: precision: 100.00%; recall: 100.00%; FB1: 100.00  113

**Comment by macanv** [comment]
没有拟合呗。。。
