### ISSUE TITLE
do_train=True ?

### ISSUE THREAD

**Issue by yuanjie-ai** [macanv/BERT-BiLSTM-CRF-NER#3]
python3 bert_lstm_ner.py   \
                  --task_name="NER"  \ 
                  --do_train=True   \
                  --do_eval=True   \
                  --do_predict=True
                  --data_dir=NERdata   \
                  --vocab_file=checkpoint/vocab.txt  \ 
                  --bert_config_file=checkpoint/bert_config.json \  
                  --init_checkpoint=checkpoint/bert_model.ckpt   \
                  --max_seq_length=128   \
                  --train_batch_size=32   \
                  --learning_rate=2e-5   \
                  --num_train_epochs=3.0   \
                  --output_dir=./output/result_dir/

**Comment by macanv** [comment]
我猜想的可能情况：
       如果你之前没有训练过，直接使用的do_train=False,那么模型会进行predict，此时model_dir 是空的，estimater会init参数开始evaluate，而不是resored我们训练好的模型。具体可以看下estimater的evaluate的checkpoint_path参数：https://tensorflow.google.cn/api_docs/python/tf/estimator/Estimator
