### ISSUE TITLE
是否对nvidia fast transformer 进行了ner测试

### ISSUE THREAD

**Issue by cronousbaby** [macanv/BERT-BiLSTM-CRF-NER#305]
您好，我这段时间也对英伟达的bert加速例子进行了测试，成功编译成功后在2080ti上进行了例子中句子分类的速度测试，但是我把任务改成ner后再运行测试出现了问题，请问您做过相关的测试吗

**Comment by Originhhh** [comment]
您好，请问您加速成功了吗
