### ISSUE TITLE
已经跑起来了！

### ISSUE THREAD

**Issue by zysNLP** [macanv/BERT-BiLSTM-CRF-NER#31]
把train_batch_size调整为16，本人在11G显存GPU1080Ti跑起来了，accurcy99%，感谢！

**Comment by ArtistScript** [comment]
> 把train_batch_size调整为16，本人在11G显存GPU1080Ti跑起来了，accurcy99%，感谢！

你好，能留个联系方式吗？想向你请教一下这个模型

**Comment by zysNLP** [comment]
qq648634000，加时备注下
