### ISSUE TITLE
训练进程被killed 

### ISSUE THREAD

**Issue by WangJieWJ** [macanv/BERT-BiLSTM-CRF-NER#318]
程序运行到这里的时候，就会被Killed掉
tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
想知道是为什么吗？需要调节什么参数吗？

**Comment by JingyaXun** [comment]
请问这个问题是怎么解决的？我也遇到了相似的问题

**Comment by WangJieWJ** [comment]
> 请问这个问题是怎么解决的？我也遇到了相似的问题

是被系统killed 掉了，使用了高配置的服务器就好
