### ISSUE TITLE
除了accuracy之外其他数据均为0, 请教一下原因.

### ISSUE THREAD

**Issue by deskl0** [macanv/BERT-BiLSTM-CRF-NER#320]
processed 83963 tokens with 0 phrases; found: 0 phrases; correct: 0.
accuracy:  96.08%; precision:   0.00%; recall:   0.00%; FB1:   0.00

**Comment by macanv** [comment]
数据读取有问题，查看一下输入格式是否和读取对应

**Comment by deskl0** [comment]
我自己写了eval的部分。问题解决，多谢回复。
