### ISSUE TITLE
在Win10预训练模型时，出现打不开bert_config.json文件，查了很多资料不知道如何解决！

### ISSUE THREAD

**Issue by YanRuYu123** [macanv/BERT-BiLSTM-CRF-NER#328]
tensorflow.python.framework.errors_impl.InvalidArgumentError: NewRandomAccessFile failed to Create/Open: {D:\Model\chinese_L-12_H-768_A-12\bert_config.json} : \udcceļ\udcfe\udcc3\udcfb\udca1\udca2Ŀ¼\udcc3\udcfb\udcbb\udcf2\udcbe\udced\udcb1\udcea\udcd3﷨\udcb2\udcbb\udcd5\udcfdȷ\udca1\udca3
; Unknown error

**Comment by macanv** [comment]
这个问题我没有遇到过，你看下文件路径是否正常，我在windows上实验 没有问题的。

**Comment by iamdawn** [comment]
你好，我也出现了这个问题，你最后解决了吗？路径好像没问题
