### ISSUE TITLE
读取数据时对空格的处理好像有些问题

### ISSUE THREAD

**Issue by JuntingGuo** [macanv/BERT-BiLSTM-CRF-NER#33]
在原数据中的原文如果为空格，则在读取数据的read_data函数中，会出现错误。
![image](https://user-images.githubusercontent.com/29737578/51224843-c4d13a80-1982-11e9-988a-f243d2f2e991.png)
这个是原数据
![image](https://user-images.githubusercontent.com/29737578/51224850-cef33900-1982-11e9-8c1b-8f56ccfd83dd.png)
这个是预测后的结果

原因应该是在read_data和convert_single_example两个函数中，将字符串用空格split时出现问题。需要在语聊中提前将空格替换掉。

**Comment by macanv** [comment]
恩，所以你需要把你的数据调整为和我的一样啊，如果不一样，那就重写你自己的数据读取方法。。因为我不可能针对所有的不同格式的数据都写了方法吧~~

**Comment by JuntingGuo** [comment]
> 恩，所以你需要把你的数据调整为和我的一样啊，如果不一样，那就重写你自己的数据读取方法。。因为我不可能针对所有的不同格式的数据都写了方法吧~~

已经重写了，只是觉得可能有人会遇到和我一样的问题，所以把问题与解决方法po出来了。。非常感谢
