### ISSUE TITLE
tensorflow   不支持 AVX2 指令

### ISSUE THREAD

**Issue by 23-zhou** [macanv/BERT-BiLSTM-CRF-NER#336]
tensorflow   不支持 AVX2 指令，这个问题有遇到过吗？1.12版本的也没有官方的

**Comment by macanv** [comment]
没有遇到过呢

**Comment by 23-zhou** [comment]
你是用GPU跑的吗？
试试用CPU，Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MaCan"<notifications@github.com&gt;; 
发送时间: 2020年5月21日(星期四) 晚上6:38
收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com&gt;; 
抄送: "■★  ⒉⒊"<2324427524@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [macanv/BERT-BiLSTM-CRF-NER] tensorflow   不支持 AVX2 指令 (#336)





 
没有遇到过呢
