### ISSUE TITLE
测试发现，在这个zeromq架构中在并发数量过大的情况下会出现服务端报错直接导致服务端崩溃，而不是排队等待处理。

### ISSUE THREAD

**Issue by caseware66** [macanv/BERT-BiLSTM-CRF-NER#341]
程序的进程直接变成僵尸进程了。然后就会报连接数不够，请增加连接数。

**Comment by macanv** [comment]
是的，所以，如果是想服务化，可以参考使用https://github.com/macanv/BERT-BiLSTM-CRF-NER/blob/master/bert_base/server/simple_flask_http_service.py
