### ISSUE TITLE
部署后，提示This is a development server. Do not use it in a production deployment

### ISSUE THREAD

**Issue by modoojunko** [macanv/BERT-BiLSTM-CRF-NER#350]
先赞下这个BERT-BASE,BERT模型微调出来后，让我吃尽了部署成服务的苦头。BERT-BASE一键式成功启动起来，并且有个/encode能直接输入待预测的句子分类，完全满足我需要。

但是根据以往搞APP的经验,flask直接启动是开发模式。要用WSGI来启动才能在生产环境。

这里有现成解决办法么？

**Comment by macanv** [comment]
这个警告，可以忽略。
或者参考这里：https://stackoverflow.com/questions/51025893/flask-at-first-run-do-not-use-the-development-server-in-a-production-environmen
