### ISSUE TITLE
这样的运行结果正常吗，之后一直没反应，output文件夹有生成模型文件

### ISSUE THREAD

**Issue by Shnnosuke1800** [macanv/BERT-BiLSTM-CRF-NER#359]
<img width="1440" alt="截屏2020-08-26 下午8 31 04" src="https://user-images.githubusercontent.com/37317281/91303868-31f1b680-e7db-11ea-956e-2b5f4f551070.png">
<img width="712" alt="截屏2020-08-26 下午8 33 05" src="https://user-images.githubusercontent.com/37317281/91303978-5baadd80-e7db-11ea-90bc-b24a500c85b5.png">

**Comment by duliping** [comment]
正常，只要output文件夹由新生成的模型就是正常的。
