### ISSUE TITLE
please help me ,How can I solve this error?

### ISSUE THREAD

**Issue by liucunixn** [macanv/BERT-BiLSTM-CRF-NER#36]
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8192,3072] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node bert/encoder/layer_11/intermediate/dense/mul_1}} = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](bert/encoder/layer_11/intermediate/dense/BiasAdd, bert/encoder/layer_11/intermediate/dense/mul)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node crf_loss/Mean/_4197}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2965_crf_loss/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
----------------------------------------------------------------------------------------------------------------------------------------
this is my computer:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0  On |                  N/A |
| 27%   46C    P8    16W / 250W |    460MiB / 11175MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 25%   44C    P8    10W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
| 25%   44C    P8    20W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:0A:00.0 Off |                  N/A |
| 21%   32C    P8    17W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1117      G   /usr/lib/xorg/Xorg                           263MiB |
|    0      2047      G   compiz                                       135MiB |
|    0     19793      G   ...-token=92AF324520652561B673766DB2684322    58MiB |
+-----------------------------------------------------------------------------+

I run this program in the terminal .......

**Comment by CapitalZe** [comment]
I'm using a GTX 1050 and the only way I could do it was via Google TPU.
From there it's very straight forward.

I always get OOM using local GPU.

**Comment by macanv** [comment]
lower batch_size or max_seq_length
you may can reference this : https://github.com/google-research/bert#out-of-memory-issues
