### ISSUE TITLE
tf.sequence_mask使用是否错误？

### ISSUE THREAD

**Issue by jiangxinyang227** [macanv/BERT-BiLSTM-CRF-NER#37]
作者，您好，请问下在bert_lstm_ner.py文件中metric_fn函数中，weight=tf.sequence_mask(FLAGS.max_seq_length)是否错误，
官方API ：tf.sequence_mask(lengths, maxlen=None, dtype=tf.bool, name=None)，这里应该接受一个lengths参数，也就是一个batch_size长的列表，记录batch_size中每条序列真实的长度。
盼回复！

**Comment by macanv** [comment]
这个地方计算的是标签级别的结果，这个结果一般认为是没有用的，因为对于NER而言是计算的实体级别的，你可以全部删掉。
当然，你说的是对的。谢谢~~
