### ISSUE TITLE
在计算真实序列时不应该用input_ids，而应该用input_mask

### ISSUE THREAD

**Issue by jiangxinyang227** [macanv/BERT-BiLSTM-CRF-NER#38]
在代码中调用Blstm + crf时需要传入序列的真实长度列表，但在代码中是用input_ids来求的：
used = tf.sign(tf.abs(input_ids))
lengths = tf.reduce_sum(used, reduction_indices=1)
这个是不是应该改成：
used = tf.sign(tf.abs(input_mask))
lengths = tf.reduce_sum(used, reduction_indices=1)
因为input_mask中真实token是用1表示的，pad是用0表示的。这样调用reduce_sum函数才能得到真实的序列长度。

**Comment by macanv** [comment]
并没有问题，你可以自己试试。
