### ISSUE TITLE
UnboundLocalError = RCV1 attempt

### ISSUE THREAD

**Issue by CapitalZe** [macanv/BERT-BiLSTM-CRF-NER#39]
I'm looking at ways to fine tune with RCV1 as opposed to the supplied dev.txt, train.txt and test.txt.

I also use cased_L-24_H-1024_A-16 as opposed to the Chinese provided one.

Whether I rename the three new files (RCV1, as found and compiled [here](https://github.com/sld/torch-conv-ner/issues/1) in the second reply) as dev.txt, train.txt and test.txt or I change them from dev.txt, train.txt and test.txt to eng.testa, eng.testb and eng.train in bert_lstm_ner.py I am faced with this following error:

`UnboundLocalError: local variable 'word' referenced before assignment`

Any ideas on how to resolve this?

If I simply follow the readme then everything works fine, only once I make a change as mentioned above do I face the problem.

**Comment by macanv** [comment]
’word‘ only appears in the function of _read_data(cls, input_file):， could you provide more error information?

**Comment by CapitalZe** [comment]
Thanks for the consideration.

The full readout is:

```
(MACAN) XXXX@ubuntu:~/BERT-BiLSTM-CRF-NER$ python bert_lstm_ner.py
Traceback (most recent call last):
  File "bert_lstm_ner.py", line 859, in <module>
    tf.app.run()
  File "/home/dt-nicholas/anaconda3/envs/MACAN/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bert_lstm_ner.py", line 645, in main
    train_examples = processor.get_train_examples(FLAGS.data_dir)
  File "bert_lstm_ner.py", line 209, in get_train_examples
    self._read_data(os.path.join(data_dir, "train.txt")), "train"
  File "bert_lstm_ner.py", line 201, in _read_data
    words.append(word)
UnboundLocalError: local variable 'word' referenced before assignment
```
I read somewhere it's an issue to do with python 2 vs 3, but I am using a conda env with python 3, and can't seem to identify what else it could be.

**Comment by CapitalZe** [comment]
If I use the NERdata from [KaiZhouZau](https://github.com/kyzhouhzau/BERT-NER), the same thing happens, even though it is the identical file naming as used in this repo, although it holds the RCV1 data I extracted earlier.
It seems to be that a simple content change of either dev.txt, train.txt or test.txt results in this error.

**Comment by macanv** [comment]
if you change train.txt,dev.txt... name to your special name ,you shold change here:
 self._read_data(os.path.join(data_dir, "train.txt"), "train")  to  self._read_data(os.path.join(data_dir, "YOU SPECIAL NAME"), "train")

**Comment by CapitalZe** [comment]
I already did that and it's the same result.
Due to this, I think it's a conflict caused by the content of the files, not the naming of them.

Any other ideas?

Thanks!

**Comment by macanv** [comment]
first:
you can move the two line words.append(word) and labels.append(label) below the  label = line.strip().split(' ')[-1]
just like that:
`    def _read_data(cls, input_file):
        """Reads a BIO data."""
        with codecs.open(input_file, 'r', encoding='utf-8') as f:
            lines = []
            words = []
            labels = []
            for line in f:
                contends = line.strip()
                tokens = contends.split(' ')
                if len(tokens) == 2:
                    word = line.strip().split(' ')[0]
                    label = line.strip().split(' ')[-1]
                    words.append(word) # move to here!!!!
                    labels.append(label)
                else:
                    if len(contends) == 0:
                        l = ' '.join([label for label in labels if len(label) > 0])
                        w = ' '.join([word for word in words if len(word) > 0])
                        lines.append([l, w])
                        words = []
                        labels = []
                        continue
                if contends.startswith("-DOCSTART-"):
                    words.append('')
                    continue
            return lines`

and than you can using line of 816 to 820 of def load_data(): functon to check data read is fine.

**Comment by macanv** [comment]
first:
you can move the two line words.append(word) and labels.append(label) below the label = line.strip().split(' ')[-1]
just like that:
    def _read_data(cls, input_file):
        """Reads a BIO data."""
        with codecs.open(input_file, 'r', encoding='utf-8') as f:
            lines = []
            words = []
            labels = []
            for line in f:
                contends = line.strip()
                tokens = contends.split(' ')
                if len(tokens) == 2:
                    word = line.strip().split(' ')[0]
                    label = line.strip().split(' ')[-1]
                    words.append(word)
                    labels.append(label)
                else:
                    if len(contends) == 0:
                        l = ' '.join([label for label in labels if len(label) > 0])
                        w = ' '.join([word for word in words if len(word) > 0])
                        lines.append([l, w])
                        words = []
                        labels = []
                        continue
                if contends.startswith("-DOCSTART-"):
                    words.append('')
                    continue

            return lines

and than you can using line of 816 to 820 of def load_data(): functon to check data read is fine.

**Comment by CapitalZe** [comment]
Thank you.

It worked; incase anyone else faces the same issue.
