### ISSUE TITLE
实时预测计算部分feed-dict部分比较耗时，怎么优化？

### ISSUE THREAD

**Issue by snakecy** [macanv/BERT-BiLSTM-CRF-NER#40]

**Comment by macanv** [comment]
并没有把，，，不知道你是怎么做的。

**Comment by snakecy** [comment]
![image](https://user-images.githubusercontent.com/12490881/51720087-1bc3c780-2087-11e9-8b61-edd0994ac36d.png)
一篇文章耗时降近20s的时间？每句在feed-dict段耗时为第一个标记处

**Comment by macanv** [comment]
你这个20S 我也看不懂，，我在GPU上是10ms一条，在CPU上是200ms一条，你参考一下最新的push.
