### ISSUE TITLE
训练自己模型的问题

### ISSUE THREAD

**Issue by 2efPer** [macanv/BERT-BiLSTM-CRF-NER#42]
假设我要对植物、动物名词进行NER，请问需要多少大概多少语料做训练集？

我现在标注了十几篇文章中的植物名(B-PLANT,I-PLANT)、动物名(B-AN,I-AN)，追加到了NERdata/train.txt中，然后用bert_lstm_ner.py训练出了模型。
之后用模型想提取一些动植物名，可以识别出ORG、LOC、PER，但就是识别不出PLANT和AN？
不清楚是哪方面的问题，训练集太少吗？

**Comment by BrikerMan** [comment]
我觉得应该不要把数据追加到 NERdata/train.txt 后面，直接只用自己的数据集试试可能会比较好。

**Comment by guanshuicheng** [comment]
需要修改terminal_predict.py中的代码，我训练的模型中，56个tag，测试集的精准和召回都很高。




| |
追梦者
邮箱：18010149119@163.com
|

签名由 网易邮箱大师 定制

在2019年01月26日 23:38，Eliyar Eziz 写道：

我觉得应该不要把数据追加到 NERdata/train.txt 后面，直接只用自己的数据集试试可能会比较好。

**Comment by huangxz** [comment]
我也碰到相同的问题@2efPer，@guanshuicheng求指教，郁闷我很长时间啦，我自己新加了一些实体属性，一个识别不出来，但是LOC、ORG、PER都没问题。代码bert_lstm_ner.py和terminal_predict.py 两个文件都修改

**Comment by huangxz** [comment]
guanshuicheng，你好！能否把您修改的 terminal_predict.py  代码发出来参考一下，谢谢！

**Comment by BrikerMan** [comment]
> guanshuicheng，你好！能否把您修改的 terminal_predict.py 代码发出来参考一下，谢谢！

可以试试我开源的 [Kashgari](https://github.com/BrikerMan/Kashgari), 不需要修改代码即可实现你说的功能。直接用自己的语料训练即可。

**Comment by huangxz** [comment]
好的，非常感谢！

**Comment by huangxz** [comment]
predict_label_result 结果是OOLabel

**Comment by macanv** [comment]
@huangxz 结果OOLabel，你训练的时候不加你训练数据里面的abel的么？
