### ISSUE TITLE
测试的时候，输入的句子长度是不是有限制？

### ISSUE THREAD

**Issue by jkszw2014** [macanv/BERT-BiLSTM-CRF-NER#43]
菜鸟发问，
例如：
xxxx地名xxxx
xxxxxxxxx，xxxx地名xxxx
第二个句子“地名“识别不出来。

**Comment by macanv** [comment]
是的，最大长度为128，你可以重新训练你的模型，让max_seq_length变大。
所以对于长句子的策略是进行分句，然后再进行预测。
