### ISSUE TITLE
关于实体标签的一点小建议

### ISSUE THREAD

**Issue by huangxz** [macanv/BERT-BiLSTM-CRF-NER#44]
首先感谢作者的分享，关于实体属性现在是通过读取train文件获取标签，建议能放出配置的地方或者放出接口，大家可以根据需要自行设定。主要是在自定义进行模型训练的时候，有一些自定义的标签。

**Comment by macanv** [comment]
好的，谢谢！

**Comment by macanv** [comment]
已经增加参数label_list 可以使用命令行指定文件或者标签字符串，使用,分割
