### ISSUE TITLE
运行了24小时还没结束

### ISSUE THREAD

**Issue by liuyunwww** [macanv/BERT-BiLSTM-CRF-NER#45]
训练集和测试集都有点大，80多M和70M。

**Comment by macanv** [comment]
显卡型号？
我用P40，70M数据运行了接近两天。10个epoch也需要

**Comment by liuyunwww** [comment]
12 vCPU。
运行了快一个星期，目前是Saving checkpoints for 22000......

**Comment by macanv** [comment]
如果step在增加，就是在训练，时间长是因为你的数据和计算能力问题。不是代码问题，谢谢
