### ISSUE TITLE
where is bert_lstm_ner.py?

### ISSUE THREAD

**Issue by js418** [macanv/BERT-BiLSTM-CRF-NER#46]
请问bert_lstm_ner.py在哪里？我想自己训练数据，但是没找到bert_lstm_ner.py，是run Python3.6 site package 的bert_lstm_ner.py吗？

**Comment by macanv** [comment]
sorry, bert_lstm_ner.py 已经从代码中移除了。如果想要，尝试一下回到https://github.com/macanv/BERT-BiLSTM-CRF-NER/commit/38be0881159711231322eef4df5f15eab675f97f  这次commit
