### ISSUE TITLE
请问试过的效果咋样？

### ISSUE THREAD

**Issue by DragonAndSky** [macanv/BERT-BiLSTM-CRF-NER#5]
我试过的命名体识别效果都不太好，对于相同的中文文本，每次运行结果都不一样，有用过的哥们吗

**Comment by mymoongit** [comment]
你们是怎么训练和运行的?我的跑不起来

**Comment by qiuwei** [comment]
@q759729997 这个数字没法跟文献中的数字比较，这个代码用的是单label而不是span的F1。

**Comment by macanv** [comment]
最新的代码里追加了entity level 的评测，可以重新跑一下，epoch 可以设置大一点。

**Comment by qiuwei** [comment]
我这里跑到的最好的结果在test上也上不了0.91。

**Comment by qiuwei** [comment]
@DragonAndSky span 就是指实体的f1。 你可以看我的表格，我这边dev集上F1 最高有0.952了，但是跟作者汇报的性能还差的远呢。

**Comment by hezhihao10** [comment]
@qiuwei  请问你们是用什么设备跑起来的， 我本地titan xp运行时报OOM错误

**Comment by qiuwei** [comment]
tesla p100 @hezhihao10

**Comment by hezhihao10** [comment]
@qiuwei  谢谢 看来是我显卡显存不够

**Comment by DragonAndSky** [comment]
@qiuwei  你多长时间测完？我测了几个小时，自己改了下，预测一句话速度好慢啊，10s才出结果

**Comment by qiuwei** [comment]
@DragonAndSky p100上挺快的，跟elmo差不多，我这里32的batch size， 1min30-2min 一个epoch。
我是用的pytorch版本。

**Comment by macanv** [comment]
@qiuwei readme.txt里面是label的结果,增加了使用conllevl做评测的结果，我迭代10次，dropout设置0.5,在test上可以跑出94.x%的结果。可以看下你的代码么？

**Comment by qiuwei** [comment]
@macanv span的结果应该比label上的结果低啊， 你能把你的预测结果贴出来吗？ 

我不太相信test上能到94。

**Comment by macanv** [comment]
Label 上的结果能跑到96为啥spam 不能到94而且我换成其他数据ACE 2005做test 效果也有92%，有时间把predicted bug 修复了，一起贴实验结果。

**Comment by DragonAndSky** [comment]
@macanv 那个索引超界的问题，应该是因为结果没有进行截断，我截断了就不会出现异常，为啥我运行你的代码来预测一句话都好慢啊，是后面添加了lstm-crf层的缘故吗？

**Comment by macanv** [comment]
@DragonAndSky 如何进行截断的，可以**分享一下截断的方法**么？  预测慢加了LSTM不是主要因素，是bert本身参数就巨多，这个感觉很耗资源。

**Comment by DragonAndSky** [comment]
@macanv 就是在写入结果对的时候，判断下索引是否超过原句长度，超过就跳过这句。你比较了bert和在bert后面添加lstm crf的效果吗？是有提升吗？所以这样做？

**Comment by DragonAndSky** [comment]
@macanv             
```
        for predict_line, prediction in zip(input_examples, result):
            idx = 0
            line_token = str(predict_line.text).split(' ')
            label_token = str(predict_line.label).split(' ')
            line_token_len = len(line_token)
            if line_token_len != len(label_token):
                tf.logging.info(predict_line.text)
                tf.logging.info(predict_line.label)
            for id in prediction:
                if idx>=line_token_len:
                        break
```

**Comment by OYE93** [comment]
> @macanv 就是在写入结果对的时候，判断下索引是否超过原句长度，超过就跳过这句。你比较了bert和在bert后面添加lstm crf的效果吗？是有提升吗？所以这样做？

如果直接跳过，讲道理应该是会影响最后的评价结果的是吧？应该要有更好的解决方法 :)

**Comment by macanv** [comment]
@DragonAndSky 添加CRF的主要目的是为了避免错误的预测。这个肯定是有提升的。

**Comment by Cr3stJole** [comment]
> @DragonAndSky p100上挺快的，跟elmo差不多，我这里32的batch size， 1min30-2min 一个epoch。 我是用的pytorch版本。

请问怎么改这个项目为pytorch版本
