### ISSUE TITLE
将ner改为分类的的模式遇到的问题

### ISSUE THREAD

**Issue by chenztchan** [macanv/BERT-BiLSTM-CRF-NER#50]
我用原生的bert代码训练了一个2分类模型，准备用于意图识别，可是做在线预测的时候，在CPU的环境下，一条预测需要4s多，所以想试试这套试试。
打开服务时，是成功的。
![image](https://user-images.githubusercontent.com/45787864/52770639-983a3c80-306e-11e9-8825-d1240933f6a6.png)
但进行预测时，就一直停在这。
![image](https://user-images.githubusercontent.com/45787864/52770696-bd2eaf80-306e-11e9-8e79-93dcb4bcb636.png)
输入的都能打印出来 就是进不到下一步
![image](https://user-images.githubusercontent.com/45787864/52772913-ac813800-3074-11e9-8a3f-52261f917605.png)

**Comment by chenztchan** [comment]
![image](https://user-images.githubusercontent.com/45787864/52770848-2f9f8f80-306f-11e9-8e4f-8f6828806802.png)
我是根据你的NER 加了个CLASS

**Comment by macanv** [comment]
![image](https://user-images.githubusercontent.com/16610116/52833007-f79f5780-3115-11e9-8ff8-a85638ef9c8b.png)
这里也要相应的改。。。接收端看下数据格式如何反序列化、
