### ISSUE TITLE
如何训练自己的分类模型

### ISSUE THREAD

**Issue by Youkinnn** [macanv/BERT-BiLSTM-CRF-NER#55]

**Comment by macanv** [comment]
使用的Bert中的例子，只是在训练的时候将label_list 和id2label使用pickle序列化保存为文件。

**Comment by ZeKunZhang1998** [comment]
> 使用的Bert中的例子，只是在训练的时候将label_list 和id2label使用pickle序列化保存为文件。

请问需要在哪里修改label之类的参数吗
