### ISSUE TITLE
-model_pb_dir and -ner_model_dir error

### ISSUE THREAD

**Issue by Rock-L** [macanv/BERT-BiLSTM-CRF-NER#56]
when i start the ner server , i got the error like:
![image](https://user-images.githubusercontent.com/22190647/53157140-d5b54180-35fb-11e9-83b2-69ed257f8991.png)

the script like:
`bert-base-serving-start \
    -model_dir C:\workspace\python\BERT_Base\output\ner2 \
    -bert_model_dir F:\chinese_L-12_H-768_A-12
    -model_pb_dir C:\workspace\python\BERT_Base\model_pb_dir
    -mode NER`

what's meaning of model_pb_dir and ner_model_dir? the output file does not have such files.

thanks.

**Comment by lonelyhentai** [comment]
This bug has been fixed in newest version, but not in `bert_base` which released in pip, please use `python3 setup.py install` rather than `pip install bert_base`.
