### ISSUE TITLE
训练自己的模型 需要多少数据？

### ISSUE THREAD

**Issue by huxb23** [macanv/BERT-BiLSTM-CRF-NER#57]
大概训练了1万个字，结果如下，label2id.pkl文件才204字节，看测试程序应该是通过这个去分词的，测试的时候分不出词，请问大概需要训练多少数据才能看到效果，谢谢
训练日志
processed 1903 tokens with 287 phrases; found: 354 phrases; correct: 210.
accuracy:  84.97%; precision:  59.32%; recall:  73.17%; FB1:  65.52
              cun: precision:  13.89%; recall:  17.24%; FB1:  15.38  36
           jiedao: precision:  83.62%; recall:  97.98%; FB1:  90.23  116
               lu: precision:  48.48%; recall:  76.19%; FB1:  59.26  33
            luhao: precision:  58.82%; recall:  71.43%; FB1:  64.52  34
              poi: precision:  53.33%; recall:  65.45%; FB1:  58.78  135
测试程序日志
input the test sentence:
坤景苑7号楼2单元501
your input is:['72', '##50', '##1']
[['O', 'O', 'O']]

**Comment by macanv** [comment]
1. 多少数据能训练一个模型： 一条数据也能训练模型，但是泛化能力不一定好
2. 你的输入切字有问题吧~~
3. 关于数字和英文还有OOV字的处理，需要更多的细节。

**Comment by huxb23** [comment]
关于数字和英文还有OOV字的处理，需要更多的细节。
这个怎么处理？

**Comment by macanv** [comment]
暂时是对于oov词使用的unk代替
对于数字，你可以自定义分字
