### ISSUE TITLE
训练自己数据模型问题

### ISSUE THREAD

**Issue by lotushacker** [macanv/BERT-BiLSTM-CRF-NER#58]
您好，使用的您这个ner模型做主干提取(删字)的训练，标签集：["Y", "N", "X", "[CLS]", "[SEP]"], 训练数据句子对每个字打上Y或者N来标识是否作为提取之后的句子主干内容，train9w/dev3w/test3w，训练完后效果如下：
![2019-02-21 20 27 47](https://user-images.githubusercontent.com/16223730/53169201-90067200-3617-11e9-8d2b-06b59bb6f99a.png)
![2019-02-21 20 31 20](https://user-images.githubusercontent.com/16223730/53169244-aad8e680-3617-11e9-845f-b03721f34633.png)
![2019-02-21 20 55 31](https://user-images.githubusercontent.com/16223730/53170595-79fab080-361b-11e9-93ee-7253ff318c85.png)

请问下精确召回都0这是什么原因的，这个是在测试集上验证的吗? 怎样修改可以输出单label的精确和召回，Y/N

另外请教下terminal_predict.py是不是不用修改像上图那样就可以预测Y/N是否保留字？如果要修改大致怎样去修改，谢谢了。

(我是用的38be088这个之前的版本，按照博客里源码训练的方式做的）

**Comment by macanv** [comment]
使用的验证效果的脚本只能识别以B- I-开头的这种标注格式，对于单一的N,Y这种标注识别不了，你可以通过对test_labels.txt中得结果进行评测，第一列是token,第二列是标注结果，第三列是预测结果。可以使用scikit-learn中的metric package

**Comment by macanv** [comment]
关于在线预测，通过convert_id_to_label函数转换成label后，你想咋处理就咋处理呗。

**Comment by macanv** [comment]
顺便请教一下，这种主干提取效果如何呢？？？
