### ISSUE TITLE
（在线等，急）为什么验证集dev和测试集test结果永远只有一次输出？想输出中间多次结果。

### ISSUE THREAD

**Issue by xinan711456** [macanv/BERT-BiLSTM-CRF-NER#59]
你好，我想在训练过程中输出验证集或测试集的中间多次准确率结果到文件中，谢谢！
以下是我的一些理解，也许错了。
（1）我的需求是，若epoch设置100，每次epoch将数据分成8批，则对验证集或测试集的准确率计算了100次或100*8次，并可以输出中间准确率到文件中。

（2）但发现bert_lstm_ner.py第112行flags.DEFINE_integer("iterations_per_loop", 1000,"How many steps to make in each estimator call.")即使设置为1，最后文件的输出都是只有1条数据（我在conlleval.py添加了open("dev.txt", "w")函数）。

通过查找发现：
bert_lstm_ner.py
681行    if FLAGS.do_train:
702行    if FLAGS.do_eval:
740 行   if FLAGS.do_predict:
大概是因为if的原因，do_train、do_eval和do_predict各自独立，意思是说flags.DEFINE_integer("iterations_per_loop"）设置的参数只对do_train模型有用，与do_eval和测试无关。

--------------------------------------------------------------------------------------------------------------

（3）代码bert_lstm_ner.py第701行 estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)，num_train_steps无论设置多少都和第702行  if FLAGS.do_eval 无关。

（4）似乎bert_lstm_ner.py第702行 if FLAGS.do_eval，永远只执行一次，即我在conlleval.py文件report_notprint函数添加文件输出函数open("dev.txt", "a+")只有一次结果。

**Comment by macanv** [comment]
1. 想输出dev每个step的信息，可以 将添加hook， 放到model_fn中，进行打印，如何写这个我真的不知道。
2. Estimator的API中表示还不知道怎么没个setp后都进行predict。不过可以开另外一个程序让-do_train -do_eval 都为False.就可以进行预测了
3. bert_lstm_ner 一共就702行，您看的哦是我的代码么？
4. do_eval 是有在模型训练结束后才进行，没有在每次写新checkpoint的跑一次。如果想，参考2

**Comment by xinan711456** [comment]
（1）我是根据博客找到你的代码的https://blog.csdn.net/macanv/article/details/85684284，应该看的是你的代码。

（2）对于这句”do_eval 是有在模型训练结束后才进行，没有在每次写新checkpoint的跑一次。如果想，参考2“，我不是很明白。是分别设置epoch为1，2，3...100，然后跑100次代码，得到100次不同epoch的结果。把100次的结果通过append附加的方式写到文件中。

（3）你的回答解决了我的疑问，非常感谢。

**Comment by macanv** [comment]
在2.中，我不知道如何增加hook在每次写新的checkpoint的时候，启动predict过程。但是可以新启动一个程序使用上面说的两个参数为False进行predict

**Comment by JuntingGuo** [comment]
> 1. 想输出dev每个step的信息，可以 将添加hook， 放到model_fn中，进行打印，如何写这个我真的不知道。
> 2. Estimator的API中表示还不知道怎么没个setp后都进行predict。不过可以开另外一个程序让-do_train -do_eval 都为False.就可以进行预测了
> 3. bert_lstm_ner 一共就702行，您看的哦是我的代码么？
> 4. do_eval 是有在模型训练结束后才进行，没有在每次写新checkpoint的跑一次。如果想，参考2

您好，https://github.com/google-research/bert/issues/70 这个链接里面的内容不知能否解决这个问题。

**Comment by macanv** [comment]
是的，可以增加hook。

**Comment by YuMiaoTHU** [comment]
请问你最终实现了可以在每个epoch或者step输出验证集结果的需求了吗？我看google上的那个回答也只是说能输出loss，但是验证集结果输出不了？

> Estimator的API中表示还不知道怎么没个setp后都进行predict。不过可以开另外一个程序让-do_train -do_eval 都为False.就可以进行预测了
这里怎么设置成每个epoch都预测一次呢？
