### ISSUE TITLE
你好，通过命令行启用时，do_train, do_predict,do_eval 三个参数永远为True

### ISSUE THREAD

**Issue by JuntingGuo** [macanv/BERT-BiLSTM-CRF-NER#60]
你好，通过命令 bert-base-ner-train -do_eval False -do_train False -do_predict True 启动预测的时候，这几个参数实际值仍然都为True.

![image](https://user-images.githubusercontent.com/29737578/53392102-5fd22100-39d3-11e9-8d2b-546fad03f90a.png)

疑似是因为 argparse包本身不支持bool类型的参数。
https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse
[https://github.com/macanv/BERT-BiLSTM-CRF-NER/blob/master/bert_base/train/train_helper.py#L40](url)

**Comment by macanv** [comment]
带上-do_train -do-eval就行了，不需要带True或者False。更多的细节，百度一下argparse的用法。

**Comment by WaNePr** [comment]
我对这部分也有疑惑，如何单独启动 e.g. do_predict，把do_train 和do_eval设置成False， 执行的时候仍然是True
