### ISSUE TITLE
请问在Linux上怎么运行bert-base-serving-start -help呢？

### ISSUE THREAD

**Issue by DukeKevin** [macanv/BERT-BiLSTM-CRF-NER#62]
请问在Linux上怎么运行bert-base-serving-start -help呢？
是进入什么目录后运行还是运行什么文件？

**Comment by macanv** [comment]
pip 安装后，就可以运行

**Comment by ares5221** [comment]
发现bert-serving-start: command not found，有人遇见过吗

**Comment by flytoylf** [comment]
安装后没有这个命令啊
bert-base-serving-start -help

**Comment by macanv** [comment]
不可能
