### ISSUE TITLE
如何获取输入字符串和输出结果的一一对应映射

### ISSUE THREAD

**Issue by symsimmy** [macanv/BERT-BiLSTM-CRF-NER#67]
现在我把测试样例成功跑起来了，但是我有两个疑问：
1.数字的识别不完整，被拆分成了几段；
2.输出结果是输入字符串中字对应的tag，想请问如何拿到tag和字符一一对应的映射。（因为一串连续的数字不能识别为一个O，所有直接映射会出错）
我的测试程序：
```
import time
from bert_base.client import BertClient
with BertClient(show_server_config=False, check_version=False, check_length=False, mode='NER') as bc:
    line = u'我叫秦始皇,请打钱,电话号码是:18654367890'
    while line:
        rst = bc.encode([line])
        print(rst)
```
比如例子：
```
我叫秦始皇,请打钱,电话号码是:18654367890
```
输出结果为：
```
[['O' 'O' 'B-PER' 'I-PER' 'I-PER' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O'
  'O' 'O' 'O' 'O' 'O' 'O']]
```
望赐教，不胜感激。

**Comment by symsimmy** [comment]
还有想请问terminal_predict如何跑起来,readme中并未提供带checkpoint的模型文件

**Comment by macanv** [comment]
1. 可以下载安装最新的0.09版本，然后在客户端就进行自定义分字，例如你的需求，就可以直接使用list
```
rst = bc.encode([list(str1)], is_tokenized=True)
```
注意需要指定is_tokenized=True

2. terminal_predict 没有测试过还能否用，可以指定目录，没问题就可以跑了。checkpoint文件需要自己训练才会有。不打算开源训练好的checkpoint文件，因为某种原因。
