### ISSUE TITLE
请问这个是不是只能在TPU条件下运行

### ISSUE THREAD

**Issue by cyl250** [macanv/BERT-BiLSTM-CRF-NER#7]
运行时候发现只能在TPU条件下。

**Comment by cyl250** [comment]
在windows下报错，AttributeError: module 'tensorflow.contrib.tpu' has no attribute 'InputPipelineConfig'

**Comment by BaiStone2017** [comment]
set --do_train=False, It can work without TPU.
While --do_train=True，it needs a long time to train?

**Comment by Zierzzz** [comment]
Hello，

> 在windows下报错，AttributeError: module 'tensorflow.contrib.tpu' has no attribute 'InputPipelineConfig'

您好 我想问一下 我也出现了这个问题，请问您解决了吗

**Comment by macanv** [comment]
建议升级一下你的TensorFlow版本，官方推荐是1.10。

**Comment by charlesfufu** [comment]
> 建议升级一下你的TensorFlow版本，官方推荐是1.10


我的Tensorflow是1.4版本也不行吗？官方版本我就不会报这个错误啊。
