### ISSUE TITLE
代码有多余的地方

### ISSUE THREAD

**Issue by cibiluozu** [macanv/BERT-BiLSTM-CRF-NER#71]
bert_base/train/lstm_crf_layer.py 中 project_crf_layer 传入的embedding_chars好像没有作用，直接用的self.embedded_chars

**Comment by macanv** [comment]
没明白您的意思

**Comment by cibiluozu** [comment]
![image](https://user-images.githubusercontent.com/10922425/53803131-ba90ed00-3f7e-11e9-989c-d2dc29c50d92.png)
这个变量在这个函数中没有用到，函数中用的是self.embedded_chars

**Comment by macanv** [comment]
恩，的确，历史遗留问题，以后看情况删不删吧~~谢谢指出
