### ISSUE TITLE
在测试集上验证的时候，如何单独启动 e.g. do_predict

### ISSUE THREAD

**Issue by WaNePr** [macanv/BERT-BiLSTM-CRF-NER#72]
把do_train 和do_eval设置成False，do_predict设置成True； 执行的时候仍然是True

**Comment by macanv** [comment]
不需要带True 命名行带上-do_train ，参数do_train就会变成False

**Comment by WaNePr** [comment]
<img width="1280" alt="screenshot 2019-03-05 at 14 02 57" src="https://user-images.githubusercontent.com/17458069/53784168-599df080-3f4f-11e9-9d8f-06ded146e1ca.png">
bert-base-ner-train: error: argument -do_train: expected one argument
