### ISSUE TITLE
do_train 不带True显示缺少参数

### ISSUE THREAD

**Issue by WaNePr** [macanv/BERT-BiLSTM-CRF-NER#75]
<img width="1280" alt="53784168-599df080-3f4f-11e9-9d8f-06ded146e1ca" src="https://user-images.githubusercontent.com/17458069/53801637-9f23e300-3f7a-11e9-9035-fe31a1a5cd93.png">
如图所示 #72

**Comment by macanv** [comment]
Sorry,这里是一个bug,你可以使用源码安装的形式，从新install这个包，然后再进行训练，bug已经修复，会在下一个版本里面进行更新
