### ISSUE TITLE
Poor accuracy on CoNLL-2003

### ISSUE THREAD

**Issue by John-Theo** [macanv/BERT-BiLSTM-CRF-NER#76]
老哥好！ Awesome project！
但是我在 CoNLL-2003 数据集上跑出来的结果似乎很糟糕。是我哪一步做错了吗？老哥有没有在 CoNLL-2003 数据集上的 NER 模型我可以复现一下正确率？

**我的数据集格式**

通过对 CoNLL-2003 数据集进行处理得到格式如下文件三份（train.txt / dev.txt / test.txt）

```
-DOCSTART- O

EU B-ORG
rejects O
German B-MISC
call O
to O
boycott O
British B-MISC
lamb O
. O

Peter B-PER
Blackburn I-PER

BRUSSELS B-LOC
1996-08-22 O

The O
European B-ORG
Commission I-ORG
……
```

**我使用的 weights**

`cased_L-12_H-768_A-12`

**我使用的参数**

所有参数均为默认

**我使用的硬件**

```
Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15129 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:03:00.0, compute capability: 6.0)
```

**我得到的 accuracy**

```
processed 46664 tokens with 5648 phrases; found: 10562 phrases; correct: 1449.
accuracy:  60.43%; precision:  13.72%; recall:  25.66%; FB1:  17.88
                 : precision:   0.00%; recall:   0.00%; FB1:   0.00  4826
              LOC: precision:  38.07%; recall:  23.92%; FB1:  29.38  1048
             MISC: precision:  25.68%; recall:  24.22%; FB1:  24.93  662
              ORG: precision:  33.65%; recall:  38.47%; FB1:  35.90  1899
              PER: precision:  11.33%; recall:  14.90%; FB1:  12.87  2127
```

**Comment by macanv** [comment]
简单来看你数据处理有问题吧，第一行是什么类型的？？建议检查一下数据读取，最大序列长度，以及训练epoch数量

**Comment by John-Theo** [comment]
https://github.com/macanv/BERT-BiLSTM-CRF-NER/blob/ff9f88a79eccbbe5f20022eb6d4407c923983a27/bert_base/train/bert_lstm_ner.py#L163-L164

第一行是 CoNLL-2003 原始数据集自带的。同时由上面代码可知，第一行即使存在也会被忽略。

另外：
`max_seq_length`: default=128
`num_train_epochs`: default=10

其他所有参数都是 `BERT-BiLSTM-CRF-NER/bert_base/train/train_helper.py` 默认的。

**Comment by macanv** [comment]
```
    : precision:   0.00%; recall:   0.00%; FB1:   0.00  4826
```
我的意思是这里的数据是什么类型的，4000多个类型的数据全部被忽略掉，您是不是要check一下呢？
因为没有试验过英文的，也不打算做这个实验，还请见谅。

**Comment by John-Theo** [comment]
这个我也不知道诶。我去数据集check一下，主要其他类型正确率也不是很高就有点疑惑。我调调参！感谢！

**Comment by rachel-sorek** [comment]
John-Theo, I have reached similarly poor quality on CoNLL 2003 set, on various combination of parameters:

> accuracy:  59.99%; precision:  15.69%; recall:  26.84%; FB1:  19.81
>                  : precision:   0.00%; recall:   0.00%; FB1:   0.00  2128
>               LOC: precision:  43.56%; recall:  37.93%; FB1:  40.55  815
>              MISC: precision:  22.83%; recall:  19.21%; FB1:  20.86  403
>               ORG: precision:  21.76%; recall:  20.36%; FB1:  21.04  579
>               PER: precision:  21.27%; recall:  23.03%; FB1:  22.12  771

and was wondering, did you managed to improved it?

**Comment by John-Theo** [comment]
I finally gave up this solution, and turned to the original BERT model. As described in their paper (BERT original paper), BERT is very good at NER tasks as it is, and no need to add fancy layers downstream. Hope it helps.

**Comment by ChenLeeStu** [comment]
我也用的CoNLL-2003数据，遇到了同样的问题：
`accuracy:  60.63%; precision:  14.67%; recall:  27.34%; FB1:  19.09
                 : precision:   0.00%; recall:   0.00%; FB1:   0.00  4727
              LOC: precision:  35.58%; recall:  28.54%; FB1:  31.67  1338
             MISC: precision:  24.84%; recall:  22.22%; FB1:  23.46  628
              ORG: precision:  39.57%; recall:  40.64%; FB1:  40.10  1706
              PER: precision:  11.13%; recall:  14.66%; FB1:  12.65  2129
`
求解。
