### ISSUE TITLE
训练后缺少label_list

### ISSUE THREAD

**Issue by luo1129** [macanv/BERT-BiLSTM-CRF-NER#77]
训练成功，但是output dir里没有label_list.pkl文件，需要自己手动创建吗，代码里也没有发现创建该文件的地方

**Comment by luo1129** [comment]
刚才那个问题解决了，出现了新的疑问，
    model_fn = model_fn_builder(
        bert_config=bert_config,
        num_labels=len(label_list)+1,
        init_checkpoint=args.init_checkpoint,
        learning_rate=args.learning_rate,
        num_train_steps=num_train_steps,
        num_warmup_steps=num_warmup_steps,
        args=args)
这里为什么要+1

**Comment by suntxy** [comment]
num_labels这个值+1会导致最后模型裁剪的时候报错，去掉+1就可以了。不清楚作者为什么+1

**Comment by macanv** [comment]
+1 是为了避免CRF解码的时候出现Nan值，@suntxy，模型剪裁错误问题已经在新版本修复。

**Comment by suntxy** [comment]
> +1 是为了避免CRF解码的时候出现Nan值，@suntxy，模型剪裁错误问题已经在新版本修复。

我是前两天下载的源码调试，ner模型需要去掉+1才可以进行裁剪，并没有在push日志中看到修复记录。

**Comment by macanv** [comment]
敢不敢好好看看，或者再试试。没修复，算我输。
