### ISSUE TITLE
中文乱码怎么破？

### ISSUE THREAD

**Issue by huxb23** [macanv/BERT-BiLSTM-CRF-NER#78]
训练之后，测试效果，发现在 bert_base/bert/tokenization.py中有中文问题，请问怎么解决？使用python3，谢谢

def _clean_text(self, text):
    """Performs invalid character removal and whitespace cleanup on text."""
    output = []
    //print(type(text)) 结果是<class 'str'>
    for char in text:
      cp = ord(char) //print(char)是乱码 而且中文拆成了3个字符
      if cp == 0 or cp == 0xfffd or _is_control(char):
        continue
      if _is_whitespace(char):
        output.append(" ")
      else:
        output.append(char)
    return "".join(output)

**Comment by macanv** [comment]
没懂啥意思。中文如何切分可以自己定，也可以使用官方的，官方的方法你可以看代码

**Comment by xiaonancs** [comment]
遇到了相同的问题
