### ISSUE TITLE
init_checkpoint文件夹内放哪些文件？

### ISSUE THREAD

**Issue by fengchi863** [macanv/BERT-BiLSTM-CRF-NER#81]
我要训练英文NER数据，下载的google bert pretrained的模型是有三个ckpt文件，这三个文件都要放进来么？因为看到源代码读取的是bert_model.ckpt，但是没有这个文件。请问这里需要怎么修改呢？修改完成之后直接使用bert-base-ner-train就可以训练自己的语料了么？

**Comment by macanv** [comment]
没用过英文，不好意思。

**Comment by zhangxiangping** [comment]
我把bert_model.ckpt.data-00000-of-00001 拷贝了一份，改成bert_model.ckpt后可以训练

**Comment by zhangxiangping** [comment]
> 我要训练英文NER数据，下载的google bert pretrained的模型是有三个ckpt文件，这三个文件都要放进来么？因为看到源代码读取的是bert_model.ckpt，但是没有这个文件。请问这里需要怎么修改呢？修改完成之后直接使用bert-base-ner-train就可以训练自己的语料了么？

我把bert_model.ckpt.data-00000-of-00001 拷贝了一份，改成bert_model.ckpt后可以训练

**Comment by fengchi863** [comment]
> 没用过英文，不好意思。

英文和中文的预训练文件夹内容是一样的，不是英文和中文的问题，那么请问作者 中文上是怎么处理的呢？chinese的预训练文件夹也是如我所描述的那样的

**Comment by fengchi863** [comment]
> > 我要训练英文NER数据，下载的google bert pretrained的模型是有三个ckpt文件，这三个文件都要放进来么？因为看到源代码读取的是bert_model.ckpt，但是没有这个文件。请问这里需要怎么修改呢？修改完成之后直接使用bert-base-ner-train就可以训练自己的语料了么？
> 
> 我把bert_model.ckpt.data-00000-of-00001 拷贝了一份，改成bert_model.ckpt后可以训练

请问结果是好的么？
