### ISSUE TITLE
bert ner

### ISSUE THREAD

**Issue by policeme** [macanv/BERT-BiLSTM-CRF-NER#82]
@macanv ![image](https://user-images.githubusercontent.com/30991932/53934516-276ec900-40de-11e9-9165-f564ad725c5e.png)
这两行代码有什么含义诶

**Comment by policeme** [comment]
@macanv 
![image](https://user-images.githubusercontent.com/30991932/53938006-d06ef100-40e9-11e9-8208-02d45f38a0bf.png)
你这里为什么要加两个全连接层，我觉得一个就够了吧。

**Comment by zhangxiangping** [comment]
> @macanv ![image](https://user-images.githubusercontent.com/30991932/53934516-276ec900-40de-11e9-9165-f564ad725c5e.png)
> 这两行代码有什么含义诶

做crf时，要获得句子的真实长度，才能进行crf解码。因为之前会用0把句子补齐到max_seq_len。
