### ISSUE TITLE
the result is all zeros

### ISSUE THREAD

**Issue by xiangwf** [macanv/BERT-BiLSTM-CRF-NER#85]
![Uploading 图片.png…]()
when I increase the learning rate ,the accuracy is improving ,but the small classes's recall and precision become 0. 
(dataset: https://github.com/kyzhouhzau/BERT-NER )
please tell me how to deal with this problem,Thanks

**Comment by xiangwf** [comment]
![图片](https://user-images.githubusercontent.com/18586019/54065641-d76b4000-425e-11e9-9dbd-de0c25999c53.png)

**Comment by macanv** [comment]
Sorry, I have not train colling-2013 data set.
