### ISSUE TITLE
再次predict的时候f1 为0

### ISSUE THREAD

**Issue by WaNePr** [macanv/BERT-BiLSTM-CRF-NER#86]
<img width="484" alt="Screenshot 2019-03-12 at 15 51 19" src="https://user-images.githubusercontent.com/17458069/54183301-d3e5ec00-44de-11e9-844a-8fdd44e888f4.png">

再次使用predict得出的f1 为0； 但是跟着train、eval、predict出来的结果显示正常。

**Comment by ArtistScript** [comment]
一样的结果，求解释一下

**Comment by macanv** [comment]
不知道两位同样的结果可不可以详细说下细节？
训练数据，参数好歹说一下吧？？？

**Comment by ArtistScript** [comment]
![image](https://user-images.githubusercontent.com/18319450/54280523-aed2a580-45d2-11e9-9507-6f5c4f3d610c.png)
train.txt dev.txt test.txt里面的内容都是重复10遍是句图片里的训练数据，句子和句子之间采用回车分隔。
训练集，验证集，测试集里的数据都是10，放在data_demo\下
训练命令是这样的
bert-base-ner-train \
    -data_dir data_demo\
    -output_dir output\
    -init_checkpoint chinese_L-12_H-768_A-12/bert_model.ckpt.index\
    -bert_config_file chinese_L-12_H-768_A-12/bert_config.json \
    -vocab_file chinese_L-12_H-768_A-12/vocab.txt

**Comment by ArtistScript** [comment]
你好，训练数据刚刚发送到你的163邮箱了，麻烦看一下，感谢~~

**Comment by macanv** [comment]
@ArtistScript  看不懂你的操作，如果你就是想玩玩，可以下载我的模型。

**Comment by ArtistScript** [comment]
能否发一下你的训练数据（或者其中一小部分）给我呢？
可能是我的训练数据格式不对（句子与句子之间）

**Comment by WaNePr** [comment]
> 能否发一下你的训练数据（或者其中一小部分）给我呢？
> 可能是我的训练数据格式不对（句子与句子之间）

不知道你是不是一样的情况，我的是do_train, do_eval, do_predict同时的时候显示的f1正常； 训练结束后想再做predict结果不正常
我的命令行如下:

python3 bert_lstm_ner.py --do_train=False --do_eval=False --do_predict=True --data_dir=data1/ --predict_batch_siz=16 --max_seq_length=128 --output_dir=result/ --data_config_path=result.config --vocal_file=chinese_L-12_H-768_A-12/vocab.txt --bert_config_file=chinese_L-12_H-768_A-12/bert_config.json

**Comment by ArtistScript** [comment]
> > 能否发一下你的训练数据（或者其中一小部分）给我呢？
> > 可能是我的训练数据格式不对（句子与句子之间）
> 
> 不知道你是不是一样的情况，我的是do_train, do_eval, do_predict同时的时候显示的f1正常； 训练结束后想再做predict结果不正常
> 我的命令行如下:
> 
> python3 bert_lstm_ner.py --do_train=False --do_eval=False --do_predict=True --data_dir=data1/ --predict_batch_siz=16 --max_seq_length=128 --output_dir=result/ --data_config_path=result.config --vocal_file=chinese_L-12_H-768_A-12/vocab.txt --bert_config_file=chinese_L-12_H-768_A-12/bert_config.json

你是怎么解决的？

**Comment by macanv** [comment]
很明显，做predict的命令用错了。

**Comment by WaNePr** [comment]
@macanv 哪里出错了，请指出
