### ISSUE TITLE
想问一下用bert中的demo:run_classifier.py微调后保存的是.ckpt文件，是怎么转化成pb文件的

### ISSUE THREAD

**Issue by jeurtr** [macanv/BERT-BiLSTM-CRF-NER#89]

**Comment by macanv** [comment]
请看代码

**Comment by zhangxiangping** [comment]
运行serving时，会将checkpoint转换为pb文件。  代码里也有写，bert_base/server/graph.py 320行左右

**Comment by jeurtr** [comment]
运行服务时转pb文件
bert_base / server / graph.py 351行
saver.restore(sess, tf.train.latest_checkpoint(args.model_dir))
model_dir 设定是加载.pkl文件 此处是否应该改为-tuned_model_dir 用来加载已经微调过的模型

**Comment by jeurtr** [comment]
@macanv  @zhangxiangping

**Comment by macanv** [comment]
pkl文件是标签和id的映射表，一个label list一个id2label，都在模型训练过程中保存的，如果你没有保存，请自己做相应的修改。

**Comment by macanv** [comment]
而且latst checkpoint的参数也不是pkl文件，建议你仔细看看呢

**Comment by jeurtr** [comment]
saver.restore(sess, tf.train.latest_checkpoint(args. model_dir))
我的意思是这个地方应该加载checkpoint文件 而不是加载.pkl文件  要不然会提示'fail to optimize the graph! %s'
