### ISSUE TITLE
用自己的数据训练的结果中存在I开头的标注序列

### ISSUE THREAD

**Issue by chgmydyh** [macanv/BERT-BiLSTM-CRF-NER#90]
按道理来说crf层应该可以避免这个情况，但是这个问题确实存在

**Comment by macanv** [comment]
这个问题在使用CRF的确不会存在，那么问题就不是CRF的问题。而是你数据或者数据切分出现的问题。更多，你可以看下其他issue，该问题已经被提问很多次了。

**Comment by chgmydyh** [comment]
好的，目前对训练数据重新处理了一遍，这个情况已经没有了，多谢。

**Comment by zhengxiaoxuer** [comment]
你好。你是怎么处理的训练数据？我现在会出现B O I I这种情况。
