### ISSUE TITLE
训练时的输出

### ISSUE THREAD

**Issue by nobrowning** [macanv/BERT-BiLSTM-CRF-NER#91]
训练开始一两个小时了，输出一直都是这样的：
![image](https://user-images.githubusercontent.com/15197290/54419801-49ea8d00-4743-11e9-95bb-b45eaaa543d0.png)
请问这样正常嘛？耗时需要一两天？

**Comment by nobrowning** [comment]
训练正常结束了。原来训练过程就这样的。。。没有训练过程的输出

**Comment by kFoodie** [comment]
一点输出都没有吗老哥？你是用 bert-base-ner-train 命令训练的吗？感觉大半天没半点反应啊。

**Comment by kFoodie** [comment]
老哥你多少数据量？训练了多久？

**Comment by nobrowning** [comment]
我的输出只有截图里的内容。还是有一些输出的，只显示添加了CUDA设备，过程中没有训练信息的输出。
我用 bert-base-ner-train 命令，人民日报的语料训练(14MB左右)。1080Ti跑了二三十分钟吧，记得不清楚了，还算快。

**Comment by kFoodie** [comment]
-verbose 这个参数是用来显示详细信息的吗？没个进度条都不知道跑到哪里，要跑多久……

**Comment by kFoodie** [comment]
我的2080Ti，参数是这样
-max_seq_length 512 \
-batch_size 8 
数据量是300M，不知道你的参数设置的是多少？

**Comment by nobrowning** [comment]
-verbose这个参数我没注意过。
我训练的时候-max_seq_length=128  -batch_size=16。我当时是修改了一下bert-base/train/train_helper.py的默认参数，然后重新pip安装了一下，再调用bert-base-ner-train命令训练的。
训练的时候，你可以看一下你自己设置的模型输出路径，检查一下里面有没有新生成一下checkpoint文件，如果有，那就是正在正常训练吧~

**Comment by kFoodie** [comment]
你是把所有的训练语料都放到train.txt里面吗？然后一句话就一个空行？

**Comment by nobrowning** [comment]
分train.txt、dev.txt、test.txt三个文件。格式如下：
{字}\t{tag}
一个字一行，句子之间用一个空行隔开

**Comment by kFoodie** [comment]
方便加你qq或者微信吗？或者你加我？54438561。
我这会参数调到batctsize=4, maxlen=64了，还是爆内存……

**Comment by kFoodie** [comment]
字跟tag的间隔我用的是空格，然后我的train.txt大小是270M，dev.txt是35M，2080Ti上一直爆内存，不知道是哪里出了问题……

**Comment by macanv** [comment]
爆内存和你的batch size 和seq length长度有关。调这些。

**Comment by kFoodie** [comment]
调好了。原来设置了CUDA_VISIBLE_DEVICES=2是没用的，要设置devicemap才有用！！。另外我发现没时间显示，没个进度条，或者不知道跑多少次，让人很绝望！！
