### ISSUE TITLE
AttributeError: training data is so small...

### ISSUE THREAD

**Issue by loveJasmine** [macanv/BERT-BiLSTM-CRF-NER#92]
C:\ub16_prj\BERT-BiLSTM-CRF-NER>bert-base-ner-train -data_dir C:\ub16_prj\BERT-NER\NERdata -output_dir output\ -init_checkpoint G:\data\chinese_L-12_H-768_A-12\bert_model.ckpt -bert_config_file G:\data\chinese_L-12_H-768_A-12\bert_config.json -vocab_file G:\data\chinese_L-12_H-768_A-12\vocab.txt
usage: C:\Users\andyy\AppData\Local\Programs\Python\Python37\Scripts\bert-base-ner-train -data_dir C:\ub16_prj\BERT-NER\NERdata -output_dir output\ -init_checkpoint G:\data\chinese_L-12_H-768_A-12\bert_model.ckpt -bert_config_file G:\data\chinese_L-12_H-768_A-12\bert_config.json -vocab_file G:\data\chinese_L-12_H-768_A-12\vocab.txt
                 ARG   VALUE
__________________________________________________
          batch_size = 64
    bert_config_file = G:\data\chinese_L-12_H-768_A-12\bert_config.json
                cell = lstm
               clean = True
                clip = 0.5
            data_dir = C:\ub16_prj\BERT-NER\NERdata
          device_map = 0
             do_eval = True
       do_lower_case = True
          do_predict = True
            do_train = True
        dropout_rate = 0.5
     filter_adam_var = False
     init_checkpoint = G:\data\chinese_L-12_H-768_A-12\bert_model.ckpt
          label_list = None
       learning_rate = 1e-05
           lstm_size = 128
      max_seq_length = 128
                 ner = ner
          num_layers = 1
    num_train_epochs = 10
          output_dir = output\
save_checkpoints_steps = 500
  save_summary_steps = 500
             verbose = False
          vocab_file = G:\data\chinese_L-12_H-768_A-12\vocab.txt
   warmup_proportion = 0.1

Traceback (most recent call last):
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\Scripts\bert-base-ner-train.exe\__main__.py", line 9, in <module>
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\bert_base\runs\__init__.py", line 38, in train_ner
    train(args=args)
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\bert_base\train\bert_lstm_ner.py", line 554, in train
    raise AttributeError('training data is so small...')
AttributeError: training data is so small...

C:\ub16_prj\BERT-BiLSTM-CRF-NER>

**Comment by macanv** [comment]
训练数据比一个batch都小，稍微看一下代码就知道咋弄。

**Comment by loveJasmine** [comment]
问题是我用的是conll2003， batch64，怎么可能呢。除非有bug

**Comment by macanv** [comment]
不保证任何格式数据都能处理，只能处理我在文档里说明的数据格式。

**Comment by LavenderZhao** [comment]
应该是文件格式问题，句子之间要加空行，文件的最后也要有空行
