### ISSUE TITLE
如何在自己的训练数据上获取训练过程的损失梯度曲线？

### ISSUE THREAD

**Issue by martin512512** [macanv/BERT-BiLSTM-CRF-NER#94]

**Comment by macanv** [comment]
不知道

**Comment by zhangxiangping** [comment]
把run_config 中的keep_max_ckpt调高点，然后进入训练好的ckpt文件夹中  用tensorboard看
![image](https://user-images.githubusercontent.com/23249742/54658412-3f940e80-4b08-11e9-92f7-8d9691262a4d.png)
最底下的那个loss应该就是train loss

**Comment by martin512512** [comment]
> run_config

谢谢您的回复！可是我没有找到run_config 文件啊？望解答，再次感谢！
