### ISSUE TITLE
通过读取train文件获取标签的方法会出现一定的风险。

### ISSUE THREAD

**Issue by Springzhen** [macanv/BERT-BiLSTM-CRF-NER#95]
Why not get tags from all data ? I think it is more easy for others to use.

**Comment by macanv** [comment]
提供了用户指定的参数，风险我也说明了。你喜欢用哪个就可以用哪个啊。。。

**Comment by Springzhen** [comment]
是从所有数据中获取标签，而不是仅仅从训练集合中获取标签，这样可以避免仅仅从训练集合获取标签时，可能会出现测试集合中部分标签不在训练集中的情况
