### ISSUE TITLE
训练准确率问题

### ISSUE THREAD

**Issue by ArtistScript** [macanv/BERT-BiLSTM-CRF-NER#96]
你好，能不能帮我看一下，训练出来的准确率为什么这么低，batchsize从16到32都试过，准确率都很低。
训练数据原封来自：https://github.com/zjy-ucas/ChineseNER里的data
训练参数：
bert-base-ner-train \
    -data_dir data\
    -output_dir output\
    -init_checkpoint chinese_L-12_H-768_A-12/bert_model.ckpt.index\
    -bert_config_file chinese_L-12_H-768_A-12/bert_config.json \
    -vocab_file chinese_L-12_H-768_A-12/vocab.txt \
    -batch_size 32 \
    -num_train_epochs=8.0 \
    -dropout_rate=0.5 \
    -max_seq_length=128
训练结果：
![image](https://user-images.githubusercontent.com/18319450/54653453-b5db4580-4af5-11e9-81bb-b33ad6bb49d7.png)
有个奇怪的地方是phraces两处不一样，我看很多人的结果两个phraces是相差不大的

**Comment by ArtistScript** [comment]
求各位解答一下TT

**Comment by ArtistScript** [comment]
TT

**Comment by ArtistScript** [comment]
没有人能解答一下吗

**Comment by macanv** [comment]
在train helper.py里头，对一些参数怎么用是有一个很具体的而且正确的默认值，你只需要按照这个改成你自己的目录就行。
但是在你的训练输入参数里，initcheckpoint存在问题。

**Comment by macanv** [comment]
而且结果正如你红线标注，数据有问题，你check一下呗。

**Comment by lichunnan** [comment]
> 你好，能不能帮我看一下，训练出来的准确率为什么这么低，batchsize从16到32都试过，准确率都很低。
> 训练数据原封来自：[https://github.com/zjy-ucas/ChineseNER里的data](https://github.com/zjy-ucas/ChineseNER%E9%87%8C%E7%9A%84data)
> 训练参数：
> bert-base-ner-train 
> -data_dir data
> -output_dir output
> -init_checkpoint chinese_L-12_H-768_A-12/bert_model.ckpt.index
> -bert_config_file chinese_L-12_H-768_A-12/bert_config.json 
> -vocab_file chinese_L-12_H-768_A-12/vocab.txt 
> -batch_size 32 
> -num_train_epochs=8.0 
> -dropout_rate=0.5 
> -max_seq_length=128
> 训练结果：
> ![image](https://user-images.githubusercontent.com/18319450/54653453-b5db4580-4af5-11e9-81bb-b33ad6bb49d7.png)
> 有个奇怪的地方是phraces两处不一样，我看很多人的结果两个phraces是相差不大的

![image](https://user-images.githubusercontent.com/33343461/56891523-53d80d80-6aaf-11e9-8e71-43f0c78981f1.png)
我的用的data和你一样，准确率也很低，请问你问题解决了么？

**Comment by ArtistScript** [comment]
> > 你好，能不能帮我看一下，训练出来的准确率为什么这么低，batchsize从16到32都试过，准确率都很低。
> > 训练数据原封来自：[https://github.com/zjy-ucas/ChineseNER里的data](https://github.com/zjy-ucas/ChineseNER%E9%87%8C%E7%9A%84data)
> > 训练参数：
> > bert-base-ner-train
> > -data_dir data
> > -output_dir output
> > -init_checkpoint chinese_L-12_H-768_A-12/bert_model.ckpt.index
> > -bert_config_file chinese_L-12_H-768_A-12/bert_config.json
> > -vocab_file chinese_L-12_H-768_A-12/vocab.txt
> > -batch_size 32
> > -num_train_epochs=8.0
> > -dropout_rate=0.5
> > -max_seq_length=128
> > 训练结果：
> > ![image](https://user-images.githubusercontent.com/18319450/54653453-b5db4580-4af5-11e9-81bb-b33ad6bb49d7.png)
> > 有个奇怪的地方是phraces两处不一样，我看很多人的结果两个phraces是相差不大的
> 
> ![image](https://user-images.githubusercontent.com/33343461/56891523-53d80d80-6aaf-11e9-8e71-43f0c78981f1.png)
> 我的用的data和你一样，准确率也很低，请问你问题解决了么？

没有额
