### ISSUE TITLE
请问如果加入其它特征应该怎么加呢？

### ISSUE THREAD

**Issue by goingcoder** [macanv/BERT-BiLSTM-CRF-NER#98]
如题，谢谢。

**Comment by macanv** [comment]
具体点，什么特征

**Comment by goingcoder** [comment]
> 具体点，什么特征

比如词性特征，加个 特征embedding，和word embedding拼接

**Comment by macanv** [comment]
直接加啊，科研问题以后都不准备回答，只解决代码bug或者使用中的问题。

**Comment by goingcoder** [comment]
> 直接加啊，科研问题以后都不准备回答，只解决代码bug或者使用中的问题。

因为这用的是高级接口，所以不知道额外特征丢进去怎么加进去，模型的地方加个embedding好，就是不太清楚怎么把特征变成数值加进去，，，，

**Comment by macanv** [comment]
使用word 2vec的时候怎么加的，这里一样怎么加，不过怎么加效果好才是问题吧~~
