### ISSUE TITLE
create_model参数数量的问题

### ISSUE THREAD

**Issue by xuanzebi** [macanv/BERT-BiLSTM-CRF-NER#99]
![image](https://user-images.githubusercontent.com/26642184/55221761-3cee9300-5245-11e9-8462-37812db502c4.png)

下图bert_base-train-bert-lstm-ner代码里的create_model
![image](https://user-images.githubusercontent.com/26642184/55221812-598acb00-5245-11e9-9484-88116f4b478c.png)
这个create_model是调用的第一张图的这个函数吧，但是参数数量不相等呀。。
第一张图的create_model只返回了一个参数呀。。

**Comment by macanv** [comment]
python 基础知识。。。

**Comment by xuanzebi** [comment]
ok...应该是rst是返回的四个组成的元组应该..
